table Dim_Proposals_Date_Combined
	lineageTag: 875e4afc-8ef2-44c2-8ebd-766992654d4d

	column New_ID
		dataType: int64
		formatString: 0
		lineageTag: 8834f6ab-9b5a-489a-bc6b-80d5ab7e362f
		summarizeBy: count
		sourceColumn: New_ID

		annotation SummarizationSetBy = Automatic

	column 'Proposal Date'
		dataType: string
		lineageTag: e1fe837d-5ed6-4b8d-b499-e954d03fab28
		summarizeBy: none
		sourceColumn: Proposal Date

		annotation SummarizationSetBy = Automatic

	column 'Created At'
		dataType: string
		lineageTag: c034f424-e89d-4ef8-92f8-3c2814bbd388
		summarizeBy: none
		sourceColumn: Created At

		annotation SummarizationSetBy = Automatic

	column 'Unified_ID '
		dataType: string
		lineageTag: 20189a8f-b331-4503-b0a7-45db43ef8130
		summarizeBy: none
		sourceColumn: "Unified_ID "

		annotation SummarizationSetBy = Automatic

	partition Dim_Proposals_Date_Combined = m
		mode: import
		queryGroup: Proposal
		source = ```
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"1-Proposals_Sheet" = Source{[Item="1-Proposals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-Proposals_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Year Stage", type any}, {"Last Submission Date", Int64.Type}, {"Submission Date Month", type text}, {"Proposal Type", type text}, {"Proposal Type PS", type text}, {"Proposal Type Code", type text}, {"Initiator", type text}, {"Initiator Type", type text}, {"Skill Sector SOP", type text}, {"Skill Sector SOP PS", type text}, {"Skill", type text}, {"Skills Revised", type text}, {"Certificate Type Proposal", type text}, {"Classify CQF Short Course", type text}, {"CQF PS", type text}, {"Exact Training Days", Int64.Type}, {"Exact Training Month", type number}, {"TotalTraining Hours", Int64.Type}, {"School Hours", Int64.Type}, {"School Practice", Int64.Type}, {"Company Practice", Int64.Type}, {"Training Type", type text}, {"Training Type PS", type text}, {"Scheme", type text}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", type number}, {"Date_Proposal Review", type any}, {"Date_LPS Review", type any}, {"Date_Appraisal", type any}, {"Date_KYC", type any}, {"Date_Pitching", type any}, {"Pitching Method", type any}, {"Date_Revision after Pitching", type any}, {"Date_Report after Pitching", type any}, {"Training Provider", type text}, {"Training Provider Type", type text}, {"Partnered Commpany", type text}, {"Enterprise Sector", type text}, {"Location", type text}, {"Cost of Proposal Riels", type number}, {"Cost of Proposal $", type number}, {"% Company", type number}, {"Company Contribution Riels", type number}, {"Company Contribution $", type number}, {"Verify Com", type any}, {"% School", type number}, {"School Contribution Riels", type number}, {"School Contribution $", type number}, {"Verify School", type any}, {"% SDF", type number}, {"SDF Contribution Riels", type number}, {"SDF Unit Cost Riels", type number}, {"SDF Contribution $", type number}, {"Verify SDF", type any}, {"SDF Unit Cost $", type number}, {"Awarded", type text}, {"Date Approved", Int64.Type}, {"Date Approved Month", type text}, {"Date_Announce", type any}, {"Budget Source", type text}, {"Trainer Fee", type number}, {"Trainee Allowance", type number}, {"Materials", type number}, {"Utilities", type number}, {"Others", type number}, {"Trainer Fee Company", type number}, {"Trainee Allowance Company", type number}, {"Materials Company", type number}, {"Utilities Company", type number}, {"Others Company", type number}, {"Trainer Fee School", type number}, {"Trainee Allowance School", type number}, {"Materials School", type number}, {"Utilities School", type number}, {"Others School", type number}, {"Trainer Fee SDF", type number}, {"Trainee Allowance SDF", type number}, {"Materials SDF", type number}, {"Utilities SDF", type number}, {"Others SDF", type number}, {"Appraisal PIC", type any}, {"Approval Duration", Int64.Type}, {"Column1", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type any}, {"Column94", type any}, {"Column95", type any}, {"Column96", type any}, {"Column97", type any}, {"Column98", type any}, {"Column99", type any}, {"Column100", type any}, {"Column101", type any}, {"Column102", type any}, {"Column103", type any}, {"Banteay Meanchey", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"ID", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"ID"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Errors", {"ID"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Year Stage", type text}, {"Last Submission Date", type date}, {"Submission Date Month", type text}, {"Female_Proposal", Int64.Type}, {"Date_Proposal Review", type date}, {"Date_LPS Review", type date}, {"Date_Appraisal", type date}, {"Date_KYC", type date}, {"Date_Pitching", type date}, {"Pitching Method", type text}, {"Date_Revision after Pitching", type date}, {"Date_Report after Pitching", type date}, {"Company Contribution $", Currency.Type}, {"Verify Com", type text}, {"School Contribution $", Currency.Type}, {"Verify School", type text}, {"SDF Contribution $", Currency.Type}, {"Verify SDF", type text}, {"SDF Unit Cost $", Currency.Type}, {"Date Approved", type date}, {"Date_Announce", type date}, {"Appraisal PIC", type text}}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Changed Type2", {"ID", "Year", "Year Stage", "Last Submission Date", "Submission Date Month", "Proposal Type", "Proposal Type PS", "Proposal Type Code", "Initiator", "Initiator Type", "Skill Sector SOP", "Skill Sector SOP PS", "Skill", "Skills Revised", "Certificate Type Proposal", "Classify CQF Short Course", "CQF PS", "Exact Training Days", "Exact Training Month", "TotalTraining Hours", "School Hours", "School Practice", "Company Practice", "Training Type", "Training Type PS", "Scheme", "Trainees_Proposal", "Female_Proposal", "Date_Proposal Review", "Date_LPS Review", "Date_Appraisal", "Date_KYC", "Date_Pitching", "Pitching Method", "Date_Revision after Pitching", "Date_Report after Pitching", "Training Provider", "Training Provider Type", "Partnered Commpany", "Enterprise Sector", "Location", "Cost of Proposal Riels", "Cost of Proposal $", "% Company", "Company Contribution Riels", "Company Contribution $", "Verify Com", "% School", "School Contribution Riels", "School Contribution $", "Verify School", "% SDF", "SDF Contribution Riels", "SDF Unit Cost Riels", "SDF Contribution $", "Verify SDF", "SDF Unit Cost $", "Awarded", "Date Approved", "Date Approved Month", "Date_Announce", "Budget Source", "Trainer Fee", "Trainee Allowance", "Materials", "Utilities", "Others", "Trainer Fee Company", "Trainee Allowance Company", "Materials Company", "Utilities Company", "Others Company", "Trainer Fee School", "Trainee Allowance School", "Materials School", "Utilities School", "Others School", "Trainer Fee SDF", "Trainee Allowance SDF", "Materials SDF", "Utilities SDF", "Others SDF", "Appraisal PIC", "Approval Duration", "Banteay Meanchey"}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Errors1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Blank Rows1"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Duplicates1",{"ID", "Date_Proposal Review", "Date_LPS Review", "Date_Appraisal", "Date_KYC", "Date_Pitching", "Date_Revision after Pitching", "Date_Report after Pitching", "Date Approved", "Date Approved Month", "Date_Announce"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Unified_ID", each "EX-" & Text.From([ID])),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Unified_ID", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type3",{"Unified_ID"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Removed Columns1",{"ID", "Date Approved"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Other Columns1",null,#date(2025, 11, 11),Replacer.ReplaceValue,{"Date Approved"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Date Approved", "Proposal Date"}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns",{{"ID", Int64.Type}}),
				    #"Removed Duplicates2" = Table.Distinct(#"Changed Type4"),
				    #"Appended Query" = Table.Combine({#"Removed Duplicates2", Dim_Proposal_Kobo_Date}),
				    #"Added Custom1" = Table.AddColumn(#"Appended Query", "Unified_ID ", each if [ID] <= 616 then "EX-" & Text.From([ID]) 
				else "KB-" & Text.From([ID])),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom1",{{"Unified_ID ", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type5",{{"ID", "New_ID"}}),
				    #"Appended Query1" = Table.Combine({#"Renamed Columns1", Dim_Proposal_Date_PMS}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Appended Query1",{"Unified_ID", "ID", "Unified_ID "}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Removed Columns2",{{"New_ID", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type6", "Unified_ID", each if [ID] <= 616 then "EX-" & Text.From([ID])
				else if [ID] <= 1000 then "KB-" & Text.From([ID])
				else "PMS-" & Text.From([ID])),
				    #"Removed Columns3" = Table.RemoveColumns(#"Added Custom2",{"Unified_ID"}),
				    #"Added Custom3" = Table.AddColumn(#"Removed Columns3", "Unified_ID ", each if [New_ID] <= 616 then "EX-" & Text.From([New_ID])
				else if [New_ID] <= 1000 then "KB-" & Text.From([New_ID])
				else "PMS-" & Text.From([New_ID]))
				in
				    #"Added Custom3"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

