table Dim_SMP_Training_Info
	lineageTag: 7e6e5285-fbe6-49dc-9e45-7c8231d30d5b

	column ID
		dataType: string
		lineageTag: 72d057ee-dcdc-4c9b-9722-5130c7b0e081
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Training Provider'
		dataType: string
		lineageTag: d02709c8-d8bc-4b34-86c3-cdbbba18bd64
		summarizeBy: none
		sourceColumn: Training Provider

		annotation SummarizationSetBy = Automatic

	column Enterprise
		dataType: string
		lineageTag: d2b265ce-b034-41fb-9989-6adf788d3bef
		summarizeBy: none
		sourceColumn: Enterprise

		annotation SummarizationSetBy = Automatic

	column 'Course Title'
		dataType: string
		lineageTag: 69eeeede-2e65-4131-84b9-b6fddfe58ed9
		summarizeBy: none
		sourceColumn: Course Title

		annotation SummarizationSetBy = Automatic

	column Session
		dataType: string
		lineageTag: 5c37d28b-4ad9-4f6c-a913-831dd9f6777b
		summarizeBy: none
		sourceColumn: Session

		annotation SummarizationSetBy = Automatic

	column 'Certificate Type'
		dataType: string
		lineageTag: db68836d-502b-4809-ab85-9fdb59efbbb8
		summarizeBy: none
		sourceColumn: Certificate Type

		annotation SummarizationSetBy = Automatic

	column 'Training Progress'
		dataType: string
		lineageTag: 691d8915-4e59-4b14-8d4c-84024724ed79
		summarizeBy: none
		sourceColumn: Training Progress

		annotation SummarizationSetBy = Automatic

	partition Dim_SMP_Training_Info = m
		mode: import
		queryGroup: 'SMP Programe'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"3-SMP Training_Sheet" = Source{[Item="3-SMP Training",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"3-SMP Training_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", type text}, {"Year", type text}, {"Year Stage", type text}, {"Training Provider", type text}, {"Enterprise", type text}, {"Course Title", type text}, {"Session", type text}, {"Unit Cost", type number}, {"Unit Cost $", Currency.Type}, {"% SDF", Percentage.Type}, {"% Employer", Percentage.Type}, {"Certificate Type", type text}, {"Start Date", type date}, {"Year Start", type text}, {"End Date", type date}, {"Year Ended", type date}, {"Training Progress", type text}, {"Track_Training Date", type text}, {"Recruited Trainees", Int64.Type}, {"Recruited Trainees Female", Int64.Type}, {"Total Cost", type number}, {"Total Cost $", Currency.Type}, {"SDF Budget", type number}, {"SDF Budget $", Currency.Type}, {"Enterprise Contribution", type number}, {"Enterprise Contribution $", Currency.Type}, {"Date Doc Submit 1st", type date}, {"Date Approved 1st Doc", type date}, {"Date Received Budget 1st", type date}, {"Disbursed 1st Riels", type number}, {"Disbursed 1st $", Currency.Type}, {"Track_Disburse 1", type text}, {"Date Doc Submit 2nd", type date}, {"Date Approved 2nd Doc", type date}, {"Date Received Budget 2nd", type date}, {"Disbursed 2nd Riels", type number}, {"Disbursed 2nd $", Currency.Type}, {"Track_Disburse 2", type text}, {"Date_Visit", type date}, {"Budget Source", type text}, {"M and E", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"M and E", null}}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Errors"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Duplicates", {"ID", "Year", "Year Stage", "Training Provider", "Enterprise", "Course Title", "Session", "Unit Cost", "Unit Cost $", "% SDF", "% Employer", "Certificate Type", "Start Date", "Year Start", "End Date", "Year Ended", "Training Progress", "Track_Training Date", "Recruited Trainees", "Recruited Trainees Female", "Total Cost", "Total Cost $", "SDF Budget", "SDF Budget $", "Enterprise Contribution", "Enterprise Contribution $", "Date Doc Submit 1st", "Date Approved 1st Doc", "Date Received Budget 1st", "Disbursed 1st Riels", "Disbursed 1st $", "Track_Disburse 1", "Date Doc Submit 2nd", "Date Approved 2nd Doc", "Date Received Budget 2nd", "Disbursed 2nd Riels", "Disbursed 2nd $", "Track_Disburse 2", "Date_Visit", "Budget Source", "M and E"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Errors"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Blank Rows",{"ID", "Training Provider", "Enterprise", "Course Title", "Session", "Certificate Type", "Training Progress"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Other Columns", {"ID"}),
				    #"Removed Duplicates3" = Table.Distinct(#"Removed Duplicates2"),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Duplicates3", {"ID", "Training Provider", "Enterprise", "Course Title", "Session", "Certificate Type", "Training Progress"}),
				    #"Removed Duplicates4" = Table.Distinct(#"Removed Errors1"),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Duplicates4", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

