table Dim_SMP_Training_disbursh
	lineageTag: 99993bc7-2ff8-4b1a-b1a3-1bc04e68df23

	column ID
		dataType: string
		lineageTag: 7399e9ff-7d2c-4f8e-9cec-221b43737cd8
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Track_Training Date'
		dataType: string
		lineageTag: 410d561b-25ee-4926-9ac4-297cfc9cb6d7
		summarizeBy: none
		sourceColumn: Track_Training Date

		annotation SummarizationSetBy = Automatic

	column 'Track_Disburse 1'
		dataType: string
		lineageTag: fb5410fc-ff52-4b19-9b4f-69b25d435482
		summarizeBy: none
		sourceColumn: Track_Disburse 1

		annotation SummarizationSetBy = Automatic

	column 'Track_Disburse 2'
		dataType: string
		lineageTag: d59d21de-3118-4831-ae51-2c6ef9868d3f
		summarizeBy: none
		sourceColumn: Track_Disburse 2

		annotation SummarizationSetBy = Automatic

	partition Dim_SMP_Training_disbursh = m
		mode: import
		queryGroup: 'SMP Programe'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"3-SMP Training_Sheet" = Source{[Item="3-SMP Training",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"3-SMP Training_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", type text}, {"Year", type text}, {"Year Stage", type text}, {"Training Provider", type text}, {"Enterprise", type text}, {"Course Title", type text}, {"Session", type text}, {"Unit Cost", type number}, {"Unit Cost $", Currency.Type}, {"% SDF", Percentage.Type}, {"% Employer", Percentage.Type}, {"Certificate Type", type text}, {"Start Date", type date}, {"Year Start", type text}, {"End Date", type date}, {"Year Ended", type date}, {"Training Progress", type text}, {"Track_Training Date", type text}, {"Recruited Trainees", Int64.Type}, {"Recruited Trainees Female", Int64.Type}, {"Total Cost", type number}, {"Total Cost $", Currency.Type}, {"SDF Budget", type number}, {"SDF Budget $", Currency.Type}, {"Enterprise Contribution", type number}, {"Enterprise Contribution $", Currency.Type}, {"Date Doc Submit 1st", type date}, {"Date Approved 1st Doc", type date}, {"Date Received Budget 1st", type date}, {"Disbursed 1st Riels", type number}, {"Disbursed 1st $", Currency.Type}, {"Track_Disburse 1", type text}, {"Date Doc Submit 2nd", type date}, {"Date Approved 2nd Doc", type date}, {"Date Received Budget 2nd", type date}, {"Disbursed 2nd Riels", type number}, {"Disbursed 2nd $", Currency.Type}, {"Track_Disburse 2", type text}, {"Date_Visit", type date}, {"Budget Source", type text}, {"M and E", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"M and E", null}}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Errors"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Duplicates", {"ID", "Year", "Year Stage", "Training Provider", "Enterprise", "Course Title", "Session", "Unit Cost", "Unit Cost $", "% SDF", "% Employer", "Certificate Type", "Start Date", "Year Start", "End Date", "Year Ended", "Training Progress", "Track_Training Date", "Recruited Trainees", "Recruited Trainees Female", "Total Cost", "Total Cost $", "SDF Budget", "SDF Budget $", "Enterprise Contribution", "Enterprise Contribution $", "Date Doc Submit 1st", "Date Approved 1st Doc", "Date Received Budget 1st", "Disbursed 1st Riels", "Disbursed 1st $", "Track_Disburse 1", "Date Doc Submit 2nd", "Date Approved 2nd Doc", "Date Received Budget 2nd", "Disbursed 2nd Riels", "Disbursed 2nd $", "Track_Disburse 2", "Date_Visit", "Budget Source", "M and E"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Errors"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Blank Rows",{"ID", "Track_Training Date", "Track_Disburse 1", "Track_Disburse 2"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Other Columns", {"ID"}),
				    #"Removed Duplicates3" = Table.Distinct(#"Removed Duplicates2"),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Duplicates3", {"ID", "Track_Training Date", "Track_Disburse 1", "Track_Disburse 2"}),
				    #"Removed Duplicates4" = Table.Distinct(#"Removed Errors1"),
				    #"Removed Errors2" = Table.RemoveRowsWithErrors(#"Removed Duplicates4", {"ID", "Track_Training Date", "Track_Disburse 1", "Track_Disburse 2"}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Errors2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

