table Dim_SMP_Date
	lineageTag: 91119f12-f6a5-4c56-90e2-4cb6faecc399

	column ID
		dataType: string
		lineageTag: ccfaa0a1-3c96-4110-a64c-7090508d9375
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 97773912-a835-4fcb-8069-978d3e3c7d06
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Stage'
		dataType: string
		lineageTag: 018930b7-be34-47ba-895a-4fa25660eb19
		summarizeBy: none
		sourceColumn: Year Stage

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: 53198e65-57bf-4c4e-acd7-c31a76c1e18b
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Application Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48b55a67-5596-417f-a439-876c3ef88789
		summarizeBy: none
		sourceColumn: Application Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Approved Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d31164d2-5ae5-476f-9049-8effc6148daf
		summarizeBy: none
		sourceColumn: Approved Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Dim_SMP_Date = m
		mode: import
		queryGroup: 'SMP Programe'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"1-SMP_Application_Sheet" = Source{[Item="1-SMP_Application",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-SMP_Application_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Hours/Day/Month", type text}, {"Unit Cost", type number}, {"Total Min Trainee", Int64.Type}, {"% SDF", type number}, {"% Employer", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"% Employer", null}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Errors",{{"Certificate Type", type text}}),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Changed Type1", {{"Unit Cost", null}}),
				    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Replaced Errors1", {{"% SDF", null}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Errors2",{{"Result", type text}, {"Approved Date", type date}, {"Approval Time", type text}, {"Budget Source", type text}, {"ID", type text}, {"Year", type text}, {"Year Stage", type text}, {"Code", type text}, {"Application Date", type date}, {"Training Provider", type text}, {"Training Provider Type", type text}, {"Sector", type text}, {"Contact Person", type text}, {"Email", type text}, {"Phone", type text}, {"Course Title", type text}, {"Hours/Session", type number}, {"Theory", type number}, {"Practice", type number}, {"Training Days/Session", type text}, {"Training Length M", type number}, {"Hours/Day/Month", type text}}),
				    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Changed Type2", {{"Hours/Session", null}}),
				    #"Replaced Errors4" = Table.ReplaceErrorValues(#"Replaced Errors3", {{"Theory", null}}),
				    #"Replaced Errors5" = Table.ReplaceErrorValues(#"Replaced Errors4", {{"Training Length M", null}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Errors5",{"ID", "Year", "Year Stage", "Code", "Application Date", "Approved Date"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"ID"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Blank Rows", {"ID", "Year", "Year Stage", "Code", "Application Date", "Approved Date"}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Errors", {"ID", "Year", "Year Stage", "Code", "Application Date", "Approved Date"})
				in
				    #"Removed Errors1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

