table Dim_KPI_Commit
	lineageTag: 825adaed-d548-4055-b500-4435cf2643a3

	column ID
		dataType: string
		lineageTag: 266b99bb-3389-43a4-85da-e362dd59f78c
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Attendance Rate Commit'
		dataType: double
		lineageTag: 4747db02-d2e4-4ccc-a3e3-2805b7ed2966
		summarizeBy: sum
		sourceColumn: Attendance Rate Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drop-out (%) Commit'
		dataType: double
		lineageTag: 87d31535-1aaa-42ba-bc0c-4bf36baea215
		summarizeBy: sum
		sourceColumn: Drop-out (%) Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Graduation Rate Commit'
		dataType: double
		lineageTag: 0232af61-c809-4de1-8155-28d710523f1b
		summarizeBy: sum
		sourceColumn: Graduation Rate Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Employment (%) Commit'
		dataType: double
		lineageTag: 011cef5c-edff-4f14-b577-5c991976376d
		summarizeBy: sum
		sourceColumn: Employment (%) Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Satisfaction Commit'
		dataType: double
		lineageTag: cb728c17-b0a9-41d1-a666-825db1ee7bbd
		summarizeBy: sum
		sourceColumn: Satisfaction Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Salary Commit $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 37af264d-6dee-445a-b925-2a9e2cc189ca
		summarizeBy: sum
		sourceColumn: Salary Commit $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column '%Salary Increase Commit'
		dataType: double
		lineageTag: 312d57f6-28f8-4dda-b59a-c3902bbfac59
		summarizeBy: sum
		sourceColumn: %Salary Increase Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Track_KPI Commit'
		dataType: string
		lineageTag: de75e952-268d-4ae2-ac7c-9a379bea9a4e
		summarizeBy: none
		sourceColumn: Track_KPI Commit

		annotation SummarizationSetBy = Automatic

	partition Dim_KPI_Commit = m
		mode: import
		queryGroup: 'KPI Monitoring'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"3-KPI Monitoring_Sheet" = Source{[Item="3-KPI Monitoring",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"3-KPI Monitoring_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Contract #", type any}, {"Initiator", type any}, {"Skill Sector SOP", type any}, {"Proposal Type PS", type any}, {"Skill", type any}, {"Scheme", type any}, {"Training Type", type any}, {"Track_Contract Duration", type text}, {"Training Progress", type text}, {"Disbursement Progress", type text}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", type number}, {"Column2", Int64.Type}, {"Column1", type text}, {"Trainee Actual", Int64.Type}, {"Female Actual", Int64.Type}, {"Terminate", Int64.Type}, {"Dead", Int64.Type}, {"Resigned", Int64.Type}, {"Attendance Rate Commit", type number}, {"Drop-out (%) Commit", type number}, {"Graduation Rate Commit", type number}, {"Employment (%) Commit", type number}, {"Satisfaction Commit", type number}, {"Salary Commit $", Int64.Type}, {"%Salary Increase Commit", type number}, {"Track_KPI Commit", type text}, {"Attendance Report", Int64.Type}, {"Attendance Report F", Int64.Type}, {"Attendance Report Rate", type text}, {"Drop-out Report", Int64.Type}, {"Drop-out Report F", Int64.Type}, {"Drop-out Report Rate", type text}, {"Graduation Report", Int64.Type}, {"Graduation Report F", Int64.Type}, {"Graduation Report Rate", type text}, {"Employment Report", Int64.Type}, {"Employment Report F", Int64.Type}, {"Employment Report Rate", type text}, {"Track_KPI Report", type text}, {"Satisfaction Report", type number}, {"Satisfaction Report Rate", type text}, {"Attendance Rate Actual", type any}, {"Attendance Rate Actual Result", type text}, {"Drop-out (%) Actual", type number}, {"Drop-out Actual Result", type text}, {"Graduation % Actual", type number}, {"Graduation (%) Actual Result", type text}, {"Employment (%) Actual", type number}, {"Emaployment (%) Actual Result", type text}, {"Salary Actual", Int64.Type}, {"Salary Actual Result", type text}, {"% Salary Increase Actual", type number}, {"% Salary Increase Actual Result", type text}, {"Track_KPI Actual", type text}, {"Tracer Study", type text}, {"Track_Feeback", type text}, {"Budget Source", type any}, {"Focal M&E", type any}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ID", type text}, {"Contract #", type text}, {"Initiator", type text}, {"Skill Sector SOP", type text}, {"Proposal Type PS", type text}, {"Skill", type text}, {"Scheme", type text}, {"Training Type", type text}, {"Track_Contract Duration", type text}, {"Female_Proposal", Int64.Type}, {"Salary Commit $", Currency.Type}, {"Attendance Report Rate", type number}, {"Attendance Report F", type number}, {"Drop-out Report", type number}, {"Drop-out Report F", type number}, {"Graduation Report F", type number}, {"Attendance Rate Actual", type number}, {"Attendance Rate Actual Result", type number}, {"Drop-out (%) Actual", type number}, {"Drop-out Actual Result", type text}, {"Graduation (%) Actual Result", type text}, {"Salary Actual", type number}, {"Budget Source", type text}, {"Focal M&E", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"ID", "Year", "Contract #", "Initiator", "Skill Sector SOP", "Proposal Type PS", "Skill", "Scheme", "Training Type", "Track_Contract Duration", "Training Progress", "Disbursement Progress", "Trainees_Proposal", "Female_Proposal", "Column2", "Column1", "Trainee Actual", "Female Actual", "Terminate", "Dead", "Resigned", "Attendance Rate Commit", "Drop-out (%) Commit", "Graduation Rate Commit", "Employment (%) Commit", "Satisfaction Commit", "Salary Commit $", "%Salary Increase Commit", "Track_KPI Commit", "Attendance Report", "Attendance Report F", "Attendance Report Rate", "Drop-out Report", "Drop-out Report F", "Drop-out Report Rate", "Graduation Report", "Graduation Report F", "Graduation Report Rate", "Employment Report", "Employment Report F", "Employment Report Rate", "Track_KPI Report", "Satisfaction Report", "Satisfaction Report Rate", "Attendance Rate Actual", "Attendance Rate Actual Result", "Drop-out (%) Actual", "Drop-out Actual Result", "Graduation % Actual", "Graduation (%) Actual Result", "Employment (%) Actual", "Emaployment (%) Actual Result", "Salary Actual", "Salary Actual Result", "% Salary Increase Actual", "% Salary Increase Actual Result", "Track_KPI Actual", "Tracer Study", "Track_Feeback", "Budget Source", "Focal M&E"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Blank Rows"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Duplicates",{"ID", "Attendance Rate Commit", "Drop-out (%) Commit", "Graduation Rate Commit", "Employment (%) Commit", "Satisfaction Commit", "Salary Commit $", "%Salary Increase Commit", "Track_KPI Commit"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

