table Dim_Proposals_Training
	lineageTag: 2ef50a17-d367-4f38-a018-9f48d2e5edb8

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b30a4635-de79-4219-acb8-6e0bb4add2b5
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Exact Training Days'
		dataType: int64
		formatString: 0
		lineageTag: c91dfbc0-1539-401a-a658-bc6beea06c82
		summarizeBy: sum
		sourceColumn: Exact Training Days

		annotation SummarizationSetBy = Automatic

	column 'Exact Training Month'
		dataType: double
		lineageTag: e41ed0ab-1075-4aad-a058-7a265157012c
		summarizeBy: sum
		sourceColumn: Exact Training Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TotalTraining Hours'
		dataType: int64
		formatString: 0
		lineageTag: ee57d26b-5fe1-4dc3-bcbf-908b32fea53e
		summarizeBy: sum
		sourceColumn: TotalTraining Hours

		annotation SummarizationSetBy = Automatic

	column 'School Hours'
		dataType: int64
		formatString: 0
		lineageTag: 83c8640f-2bbf-4a73-b267-b531bc5f8330
		summarizeBy: sum
		sourceColumn: School Hours

		annotation SummarizationSetBy = Automatic

	column 'School Practice'
		dataType: int64
		formatString: 0
		lineageTag: 31415ae3-0d24-4ba0-9643-c773d641dba0
		summarizeBy: sum
		sourceColumn: School Practice

		annotation SummarizationSetBy = Automatic

	column 'Company Practice'
		dataType: int64
		formatString: 0
		lineageTag: 4d5cfac3-ceb8-4fa3-b792-951b4233ae90
		summarizeBy: sum
		sourceColumn: Company Practice

		annotation SummarizationSetBy = Automatic

	column 'Training Type'
		dataType: string
		lineageTag: af8fd934-fab4-4d79-b565-8e1b2c94bb0c
		summarizeBy: none
		sourceColumn: Training Type

		annotation SummarizationSetBy = Automatic

	column 'Training Type PS'
		dataType: string
		lineageTag: 58811d72-8a13-4d31-8cef-53bc2a39bf82
		summarizeBy: none
		sourceColumn: Training Type PS

		annotation SummarizationSetBy = Automatic

	column Trainees_Proposal
		dataType: int64
		formatString: 0
		lineageTag: c457b445-711d-4a83-b2b3-36d36650b921
		summarizeBy: sum
		sourceColumn: Trainees_Proposal

		annotation SummarizationSetBy = Automatic

	column Female_Proposal
		dataType: int64
		formatString: 0
		lineageTag: 5beff1a6-362c-4759-80ad-612b28e53ded
		summarizeBy: sum
		sourceColumn: Female_Proposal

		annotation SummarizationSetBy = Automatic

	column 'Unified_ID '
		dataType: string
		lineageTag: b907e7ce-07bf-4b47-bb02-b73275c174a9
		summarizeBy: none
		sourceColumn: "Unified_ID "

		annotation SummarizationSetBy = Automatic

	partition Dim_Proposals_Training = m
		mode: import
		queryGroup: Proposal
		source = ```
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"1-Proposals_Sheet" = Source{[Item="1-Proposals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"1-Proposals_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Year Stage", type any}, {"Last Submission Date", Int64.Type}, {"Submission Date Month", type text}, {"Proposal Type", type text}, {"Proposal Type PS", type text}, {"Proposal Type Code", type text}, {"Initiator", type text}, {"Initiator Type", type text}, {"Skill Sector SOP", type text}, {"Skill Sector SOP PS", type text}, {"Skill", type text}, {"Skills Revised", type text}, {"Certificate Type Proposal", type text}, {"Classify CQF Short Course", type text}, {"CQF PS", type text}, {"Exact Training Days", Int64.Type}, {"Exact Training Month", type number}, {"TotalTraining Hours", Int64.Type}, {"School Hours", Int64.Type}, {"School Practice", Int64.Type}, {"Company Practice", Int64.Type}, {"Training Type", type text}, {"Training Type PS", type text}, {"Scheme", type text}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", type number}, {"Date_Proposal Review", type any}, {"Date_LPS Review", type any}, {"Date_Appraisal", type any}, {"Date_KYC", type any}, {"Date_Pitching", type any}, {"Pitching Method", type any}, {"Date_Revision after Pitching", type any}, {"Date_Report after Pitching", type any}, {"Training Provider", type text}, {"Training Provider Type", type text}, {"Partnered Commpany", type text}, {"Enterprise Sector", type text}, {"Location", type text}, {"Cost of Proposal Riels", type number}, {"Cost of Proposal $", type number}, {"% Company", type number}, {"Company Contribution Riels", type number}, {"Company Contribution $", type number}, {"Verify Com", type any}, {"% School", type number}, {"School Contribution Riels", type number}, {"School Contribution $", type number}, {"Verify School", type any}, {"% SDF", type number}, {"SDF Contribution Riels", type number}, {"SDF Unit Cost Riels", type number}, {"SDF Contribution $", type number}, {"Verify SDF", type any}, {"SDF Unit Cost $", type number}, {"Awarded", type text}, {"Date Approved", Int64.Type}, {"Date Approved Month", type text}, {"Date_Announce", type any}, {"Budget Source", type text}, {"Trainer Fee", type number}, {"Trainee Allowance", type number}, {"Materials", type number}, {"Utilities", type number}, {"Others", type number}, {"Trainer Fee Company", type number}, {"Trainee Allowance Company", type number}, {"Materials Company", type number}, {"Utilities Company", type number}, {"Others Company", type number}, {"Trainer Fee School", type number}, {"Trainee Allowance School", type number}, {"Materials School", type number}, {"Utilities School", type number}, {"Others School", type number}, {"Trainer Fee SDF", type number}, {"Trainee Allowance SDF", type number}, {"Materials SDF", type number}, {"Utilities SDF", type number}, {"Others SDF", type number}, {"Appraisal PIC", type any}, {"Approval Duration", Int64.Type}, {"Column1", type any}, {"Column86", type any}, {"Column87", type any}, {"Column88", type any}, {"Column89", type any}, {"Column90", type any}, {"Column91", type any}, {"Column92", type any}, {"Column93", type any}, {"Column94", type any}, {"Column95", type any}, {"Column96", type any}, {"Column97", type any}, {"Column98", type any}, {"Column99", type any}, {"Column100", type any}, {"Column101", type any}, {"Column102", type any}, {"Column103", type any}, {"Banteay Meanchey", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"ID", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"ID"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Errors", {"ID"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Year Stage", type text}, {"Last Submission Date", type date}, {"Submission Date Month", type text}, {"Female_Proposal", Int64.Type}, {"Date_Proposal Review", type date}, {"Date_LPS Review", type date}, {"Date_Appraisal", type date}, {"Date_KYC", type date}, {"Date_Pitching", type date}, {"Pitching Method", type text}, {"Date_Revision after Pitching", type date}, {"Date_Report after Pitching", type date}, {"Company Contribution $", Currency.Type}, {"Verify Com", type text}, {"School Contribution $", Currency.Type}, {"Verify School", type text}, {"SDF Contribution $", Currency.Type}, {"Verify SDF", type text}, {"SDF Unit Cost $", Currency.Type}, {"Date Approved", type date}, {"Date_Announce", type date}, {"Appraisal PIC", type text}}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Changed Type2", {"ID", "Year", "Year Stage", "Last Submission Date", "Submission Date Month", "Proposal Type", "Proposal Type PS", "Proposal Type Code", "Initiator", "Initiator Type", "Skill Sector SOP", "Skill Sector SOP PS", "Skill", "Skills Revised", "Certificate Type Proposal", "Classify CQF Short Course", "CQF PS", "Exact Training Days", "Exact Training Month", "TotalTraining Hours", "School Hours", "School Practice", "Company Practice", "Training Type", "Training Type PS", "Scheme", "Trainees_Proposal", "Female_Proposal", "Date_Proposal Review", "Date_LPS Review", "Date_Appraisal", "Date_KYC", "Date_Pitching", "Pitching Method", "Date_Revision after Pitching", "Date_Report after Pitching", "Training Provider", "Training Provider Type", "Partnered Commpany", "Enterprise Sector", "Location", "Cost of Proposal Riels", "Cost of Proposal $", "% Company", "Company Contribution Riels", "Company Contribution $", "Verify Com", "% School", "School Contribution Riels", "School Contribution $", "Verify School", "% SDF", "SDF Contribution Riels", "SDF Unit Cost Riels", "SDF Contribution $", "Verify SDF", "SDF Unit Cost $", "Awarded", "Date Approved", "Date Approved Month", "Date_Announce", "Budget Source", "Trainer Fee", "Trainee Allowance", "Materials", "Utilities", "Others", "Trainer Fee Company", "Trainee Allowance Company", "Materials Company", "Utilities Company", "Others Company", "Trainer Fee School", "Trainee Allowance School", "Materials School", "Utilities School", "Others School", "Trainer Fee SDF", "Trainee Allowance SDF", "Materials SDF", "Utilities SDF", "Others SDF", "Appraisal PIC", "Approval Duration", "Banteay Meanchey"}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Errors1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Blank Rows1"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Duplicates1",{"ID", "Exact Training Days", "Exact Training Month", "TotalTraining Hours", "School Hours", "School Practice", "Company Practice", "Training Type", "Training Type PS", "Trainees_Proposal", "Female_Proposal"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Unified_ID", each "EX-" & Text.From([ID])),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Unified_ID", type text}, {"ID", Int64.Type}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type3",{"Unified_ID"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns1", "Unified_ID ", each if [ID] <= 616 then "EX-" & Text.From([ID]) 
				else "KB-" & Text.From([ID]))
				in
				    #"Added Custom1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

