table Dim_SBJ_Date
	lineageTag: a6e39332-ba5f-4177-ab8e-e76963d96424

	column 'Training Provider'
		dataType: string
		lineageTag: 3a49575b-e8ee-4b99-85df-d4cf23fddb7f
		summarizeBy: none
		sourceColumn: Training Provider

		annotation SummarizationSetBy = Automatic

	column 'Date of training start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 30a9b858-79b7-4e34-8861-fe3bc05d599e
		summarizeBy: none
		sourceColumn: Date of training start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column No
		dataType: int64
		formatString: 0
		lineageTag: c90986e4-82cc-4dc3-b423-6b47fa83f4da
		summarizeBy: none
		sourceColumn: No

		annotation SummarizationSetBy = Automatic

	partition Dim_SBJ_Date = m
		mode: import
		queryGroup: 'SBJ Project'
		source =
				let
				    Source = Fact_SBJ_Progress,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Training Provider", "Date of training start"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "No"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

