table Dim_Proposals_Awarded_Combined
	lineageTag: 94a287e1-cf78-41cc-a519-cda456abb62e

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 64da70b0-e4ee-40cd-a245-0cff0d84e731
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Awarded
		dataType: string
		lineageTag: a2005c29-390c-4d31-8d4d-3fd088131fad
		summarizeBy: none
		sourceColumn: Awarded

		annotation SummarizationSetBy = Automatic

	partition Dim_Proposals_Awarded_Combined = m
		mode: import
		queryGroup: Proposal
		source =
				let
				    Source = Fact_Proposals_Cost,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Awarded"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Blank Rows"),
				    #"Appended Query" = Table.Combine({#"Removed Duplicates1", Dim_Proposal_Awarded_kobo}),
				    #"Removed Duplicates2" = Table.Distinct(#"Appended Query"),
				    #"Removed Duplicates3" = Table.Distinct(#"Removed Duplicates2"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Duplicates3", {"ID", "Awarded"}),
				    #"Removed Duplicates4" = Table.Distinct(#"Removed Errors", {"ID"}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Removed Duplicates4", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates5" = Table.Distinct(#"Removed Blank Rows1"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates5",{{"ID", Int64.Type}}),
				    #"Removed Duplicates6" = Table.Distinct(#"Changed Type")
				in
				    #"Removed Duplicates6"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

