table Dim_Location_SKey
	lineageTag: c4c1897c-0a14-4bb5-9244-dc103e16c658

	column ID
		dataType: string
		lineageTag: 643b178a-8a49-4d8a-997d-8b71d3c69ced
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Contract #'
		dataType: string
		lineageTag: dbffdb47-619f-4585-b799-449e32c1b586
		summarizeBy: none
		sourceColumn: Contract #

		annotation SummarizationSetBy = Automatic

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 1462ac5e-f342-437c-a254-eed1c81c77a4
		summarizeBy: count
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Location_SKey = m
		mode: import
		queryGroup: Laction_info
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"6-Location_Sheet" = Source{[Item="6-Location",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"6-Location_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Year Stage", type any}, {"Contract #", type text}, {"Skill Sector SOP", type text}, {"Proposal Type PS", type any}, {"Initiator", type text}, {"Skill", type text}, {"SDF Contribution $", type number}, {"Trainee Proposal", Int64.Type}, {"Female Proposal", Int64.Type}, {"Trainee Actual", Int64.Type}, {"Female Actual", Int64.Type}, {"Location", type text}, {"Track_Location", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ID", type text}, {"Year Stage", type text}, {"Proposal Type PS", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type1", {{"SDF Contribution $", null}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Replaced Errors", {"ID", "Year", "Year Stage", "Contract #", "Skill Sector SOP", "Proposal Type PS", "Initiator", "Skill", "SDF Contribution $", "Trainee Proposal", "Female Proposal", "Trainee Actual", "Female Actual", "Location", "Track_Location"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Blank Rows",{{"Year", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type2",{"ID", "Contract #"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Location_SKey"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

