table Dim_Training_info_PMS
	lineageTag: 742d880a-45ce-4158-90a9-269ba78ba844

	column 'Proposal ID'
		dataType: int64
		formatString: 0
		lineageTag: 05b08934-1116-4c1a-baf8-98624c5c481b
		summarizeBy: count
		sourceColumn: Proposal ID

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 82fd7d79-fd7b-4228-9f22-493e539c2008
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Institute Name'
		dataType: string
		lineageTag: 18c25f64-2ff1-4c6a-941f-18349a2a9161
		summarizeBy: none
		sourceColumn: Institute Name

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: cbf32fb1-0e88-40cf-8b38-5f5189984f0c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Staff
		dataType: int64
		formatString: 0
		lineageTag: d4f98faf-4708-400d-96bb-940303d28968
		summarizeBy: sum
		sourceColumn: Staff

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: a698a793-b470-414b-8ddb-e4d6dad3a481
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 8f7f7f46-feee-4cde-a443-682330db9a53
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Training Scheme'
		dataType: string
		lineageTag: 4d9da76c-4603-422c-847f-66beee364e13
		summarizeBy: none
		sourceColumn: Training Scheme

		annotation SummarizationSetBy = Automatic

	column Unified_ID
		dataType: string
		lineageTag: f5c02925-62d5-498e-be44-6dbc472300ee
		summarizeBy: none
		sourceColumn: Unified_ID

		annotation SummarizationSetBy = Automatic

	column New_ID
		dataType: string
		lineageTag: f83df6da-1c8d-46c9-8257-d9eaf7b1b091
		summarizeBy: none
		sourceColumn: New_ID

		annotation SummarizationSetBy = Automatic

	partition Dim_Training_info_PMS = m
		mode: import
		queryGroup: 'Proposal\PMS_Proposals\PMS_Data Source'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://api-gateway.sdfcambodia.org/api/ADMIN_PMS/pms/v2/proposals/excel?type=file"), null, true),
				    Data = Source[Data],
				    Data1 = Data{0},
				    #"Promoted Headers" = Table.PromoteHeaders(Data1, [PromoteAllScalars=true]),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Promoted Headers",{{"Proposal ID", Int64.Type}, {"Proposal Number", Int64.Type}, {"Proposal Code", type text}, {"Institute Name", type text}, {"Institute Name (KH)", type text}, {"Status", type text}, {"Registration No", type text}, {"Establishment Year", type date}, {"Staff", Int64.Type}, {"Sector", type text}, {"Expertise", type text}, {"Under Ministry", type text}, {"Website URL", type text}, {"Facebook URL", type text}, {"Contact Person", type text}, {"Job Title", type text}, {"Office", type text}, {"Gender", type text}, {"Telegram No", type text}, {"Email", type text}, {"Initiated By", type text}, {"Training Scheme", type text}, {"Training License", type text}, {"Province Name", type text}, {"District Name", type text}, {"Training Start Date", type date}, {"Training End Date", type date}, {"Created At", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type6",{{"Proposal Number", "ID"}, {"Institute Name (KH)", "Institute Name (Khmer)"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Training Start Date", type date}, {"Training End Date", type date}, {"Created At", type date}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Created At", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type2", {{"Created At", null}}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Errors", {"ID"}, Dim_Proposals_PMS, {"ID"}, "Dim_Proposals_PMS", JoinKind.LeftOuter),
				    #"Expanded Dim_Proposals_PMS" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Proposals_PMS", {"Province"}, {"Province"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded Dim_Proposals_PMS", "Unified_ID", each "PMS-" & Text.From([ID])),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Unified_ID", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type3", "New_ID", each [ID] + 1000),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom1",{{"New_ID", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type4",{"New_ID"}),
				    #"Added Custom2" = Table.AddColumn(#"Removed Columns", "New_ID ", each [ID] + 1000),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom2",{{"ID", Int64.Type}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type5",{"New_ID "}),
				    #"Added Custom3" = Table.AddColumn(#"Removed Columns1", "New_ID", each [ID] + 1000),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom3",{"Proposal ID", "ID", "Institute Name", "Status", "Staff", "Sector", "Gender", "Training Scheme", "Unified_ID", "New_ID"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

