table Dim_TP_Acronym_Code
	lineageTag: c2d5805c-584a-488a-8196-4620aaea2afd

	column 'Training Provider'
		dataType: string
		lineageTag: f8d982b1-efb8-45d4-a2f8-fe2a0296b82b
		summarizeBy: none
		sourceColumn: Training Provider

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: 6b689bf5-e92c-4ad9-82a7-f9783e718dbd
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Text Before Delimiter'
		dataType: string
		lineageTag: 647300f8-b825-4753-b6cf-78f19fea931b
		summarizeBy: none
		sourceColumn: Text Before Delimiter

		annotation SummarizationSetBy = Automatic

	partition Dim_TP_Acronym_Code = m
		mode: import
		queryGroup: 'SBJ Project'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\TPAcronym_processed.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Replaced Value" = Table.ReplaceValue(#"Promoted Headers","CAMBODIA","CAMMABIZ ",Replacer.ReplaceText,{"Text Before Delimiter"}),
				    #"Uppercased Text" = Table.TransformColumns(#"Replaced Value",{{"Text Before Delimiter", Text.Upper, type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Uppercased Text","CAMBODIA","CAMMABIZ",Replacer.ReplaceText,{"Text Before Delimiter"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","CAMMA","CAMMABIZ",Replacer.ReplaceText,{"Text Before Delimiter"}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Value2", {"Text Before Delimiter"}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Duplicates", {"Text Before Delimiter"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Errors", {"Text Before Delimiter"}),
				    #"Removed Duplicates2" = Table.Distinct(#"Removed Duplicates1")
				in
				    #"Removed Duplicates2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

