table Fact_Disburse_Normal
	lineageTag: 20e3ddde-53a9-4319-8f43-45bb22300dc7

	column ID
		dataType: string
		lineageTag: 18a70822-1dee-4a9a-b3c0-a305b0c34d07
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column '# Disbursements'
		dataType: int64
		formatString: 0
		lineageTag: 647f0ccd-fcb0-488c-b6a8-c59cee44b863
		summarizeBy: sum
		sourceColumn: # Disbursements

		annotation SummarizationSetBy = Automatic

	column 'Disbursed 1 Riels'
		dataType: double
		lineageTag: 3c5797ee-5544-49a1-9356-094ab4aabeda
		summarizeBy: sum
		sourceColumn: Disbursed 1 Riels

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 1 $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c0952d38-6510-49c7-83b9-71294452d78f
		summarizeBy: sum
		sourceColumn: Disbursed 1 $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Disbursed 2 Riels'
		dataType: double
		lineageTag: d413dfd8-7389-47b8-bffc-eb828ffc2eb0
		summarizeBy: sum
		sourceColumn: Disbursed 2 Riels

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 2 $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 06b02b6a-ef97-4e57-ab82-c9676f7e2f16
		summarizeBy: sum
		sourceColumn: Disbursed 2 $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Disbursed 3 Riels'
		dataType: double
		lineageTag: 7782eede-3745-440a-bbf0-94ec9cf848d0
		summarizeBy: sum
		sourceColumn: Disbursed 3 Riels

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 3 $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 96e196d6-96fe-4fc2-9226-a40cf7d67a42
		summarizeBy: sum
		sourceColumn: Disbursed 3 $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Disbursed 4 Riels'
		dataType: double
		lineageTag: e51fbd6d-047a-4b17-89a1-1c9282c90870
		summarizeBy: sum
		sourceColumn: Disbursed 4 Riels

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 4 $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: edb96589-6ced-4243-911b-2fcfa9401442
		summarizeBy: sum
		sourceColumn: Disbursed 4 $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Disbursed 1 Riels PS'
		dataType: double
		lineageTag: 7a77a3e0-296c-476d-a026-0efe18cad170
		summarizeBy: sum
		sourceColumn: Disbursed 1 Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 1 $ PS'
		dataType: double
		lineageTag: a24cb395-1aac-452d-a37a-40761d907799
		summarizeBy: sum
		sourceColumn: Disbursed 1 $ PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 2 Riels PS'
		dataType: double
		lineageTag: 135b2758-b368-4821-8fce-dccbe137852a
		summarizeBy: sum
		sourceColumn: Disbursed 2 Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 2 $ PS'
		dataType: double
		lineageTag: c058ab1d-9030-4820-a25f-c55d5f94ef1f
		summarizeBy: sum
		sourceColumn: Disbursed 2 $ PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 3 Riels PS'
		dataType: double
		lineageTag: 580f0d2b-ab62-482c-938d-dc6aa3a06eda
		summarizeBy: sum
		sourceColumn: Disbursed 3 Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 3 $ PS'
		dataType: double
		lineageTag: 8ce2de75-7cff-4fca-9f32-ab9e5353c7aa
		summarizeBy: sum
		sourceColumn: Disbursed 3 $ PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 4 Riels PS'
		dataType: double
		lineageTag: 9b6b7920-d80e-48b0-af23-5dd2d77070ae
		summarizeBy: sum
		sourceColumn: Disbursed 4 Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed 4 $ PS'
		dataType: double
		lineageTag: a8e775b1-a145-40ef-ae4a-dca9b023db7f
		summarizeBy: sum
		sourceColumn: Disbursed 4 $ PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed Budget Riels PS'
		dataType: double
		lineageTag: e26e1c65-3f21-41d3-928a-baf278a55d03
		summarizeBy: sum
		sourceColumn: Disbursed Budget Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Disbursed $ Exchange Rate PS'
		dataType: double
		lineageTag: 727c868e-b9bc-40ff-a3ab-4e2d5646bac8
		summarizeBy: sum
		sourceColumn: Disbursed $ Exchange Rate PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Track_PWS Disburse 1'
		dataType: string
		lineageTag: aec5fdb7-8d1c-43e0-a595-cfac713ca0b8
		summarizeBy: none
		sourceColumn: Track_PWS Disburse 1

		annotation SummarizationSetBy = Automatic

	column 'Track_PWS Disburse 2'
		dataType: string
		lineageTag: 0c551f02-a35d-403d-997f-1b94bbe3b45a
		summarizeBy: none
		sourceColumn: Track_PWS Disburse 2

		annotation SummarizationSetBy = Automatic

	column 'Track_PWS Disburse 3'
		dataType: string
		lineageTag: 95558d4c-7467-480a-abdd-b72c35ef3999
		summarizeBy: none
		sourceColumn: Track_PWS Disburse 3

		annotation SummarizationSetBy = Automatic

	column 'Track_PWS Disburse 4'
		dataType: string
		lineageTag: b53fc05e-8075-4494-9152-1e4c1c809b24
		summarizeBy: none
		sourceColumn: Track_PWS Disburse 4

		annotation SummarizationSetBy = Automatic

	column 'Remain Budget Riels PS'
		dataType: double
		lineageTag: 0e308574-5db4-4ed7-8a7b-ec6f5c2d0400
		summarizeBy: sum
		sourceColumn: Remain Budget Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimated Budget Riels PS'
		dataType: double
		lineageTag: b8162f16-f122-4c5a-8494-fe9c7ba62fda
		summarizeBy: sum
		sourceColumn: Estimated Budget Riels PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Remained & Estimated Budget PS'
		dataType: double
		lineageTag: d2d0704d-8b22-4c3f-8f16-26c0b0351fdb
		summarizeBy: sum
		sourceColumn: Balance Remained & Estimated Budget PS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Disburse_Normal = m
		mode: import
		queryGroup: 'Training Cost Disburshment\Deburshement Normal'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"4-Disburse_Normal_Sheet" = Source{[Item="4-Disburse_Normal",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"4-Disburse_Normal_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Year Stage", type any}, {"Proposal Type", type any}, {"Contract #", type any}, {"Initiator", type any}, {"Skill", type any}, {"Trainees_Proposal", Int64.Type}, {"SDF Contribution Riels", type number}, {"Track_Contract Duration", type text}, {"# Disbursements", Int64.Type}, {"Planned Budget 1st#(lf)(10%)", type number}, {"Expected Date 1st", Int64.Type}, {"Text_Expected Date 1st", type text}, {"Track_NP_Estimate 1", type text}, {"Date Doc Submit 1st", Int64.Type}, {"Date Approved 1st Doc", Int64.Type}, {"Date Received Budget 1st", type any}, {"Text Date Received Budget 1st", type text}, {"Disbursed 1 Riels", type number}, {"Disbursed 1 $", type number}, {"Track_NP_Disburse 1", type text}, {"Planned Budget 2nd#(lf)(40%)", type number}, {"Expected Date 2nd", Int64.Type}, {"Text_Expected Date 2nd", type text}, {"Track_NP_Estimate 2", type text}, {"Date Doc Submit 2nd", Int64.Type}, {"Date Approved 2nd Doc", Int64.Type}, {"Date Received Budget 2nd", Int64.Type}, {"Text Date Received Budget 2nd", type text}, {"Disbursed 2 Riels", type number}, {"Disbursed 2 $", type number}, {"Track_NP_Disburse 2", type text}, {"Planned Budget 3rd#(lf)(30%)", type number}, {"Expected Date 3rd", type number}, {"Track_NP_Estimate 3", type text}, {"Text_Expected Date 3rd", type text}, {"Date Doc Submit 3rd", Int64.Type}, {"Date Approved 3rd Doc", Int64.Type}, {"Date Received Budget 3rd", type any}, {"Text Date Received Budget 3rd", type text}, {"Disbursed 3 Riels", type number}, {"Disbursed 3 $", type number}, {"Track_NP_Disburse 3", type text}, {"Planned Budget 4th#(lf)(20%)", type number}, {"Expected Date 4th", Int64.Type}, {"Text_Expected Date 4th", type text}, {"Track_NP_Estimate 4", type text}, {"Date Doc Submit 4th", Int64.Type}, {"Date Approved 4th Doc", Int64.Type}, {"Date Received Budget 4th", type any}, {"Text Date Received Budget 4th", type text}, {"Disbursed 4 Riels", Int64.Type}, {"Disbursed 4 $", type number}, {"Track_NP_Disburse 4", type text}, {"Training Progress", type text}, {"Disbursement Progress", type text}, {"Disbursed Budget Riels", type number}, {"Disbursed $ Exchange Rate", type number}, {"Column1", type text}, {"%Disbursed", type any}, {"Balance Normal Riels", type number}, {"Budget Source", type any}, {"Focal M&E", type any}, {"Recruited Trainee", Int64.Type}, {"Remained Trainee", Int64.Type}, {"Estimated Trainee", Int64.Type}, {"Balanced Remained & Estimated Trainee", Int64.Type}, {"Track_PWS Estimate 1", type text}, {"Track_PWS Estimate 2", type text}, {"Track_PWS Estimate 3", type text}, {"Track_PWS Estimate 4", type text}, {"Disbursed 1 Riels PS", type number}, {"Disbursed 1 $ PS", type number}, {"Disbursed 2 Riels PS", type number}, {"Disbursed 2 $ PS", type number}, {"Disbursed 3 Riels PS", type number}, {"Disbursed 3 $ PS", type number}, {"Disbursed 4 Riels PS", Int64.Type}, {"Disbursed 4 $ PS", Int64.Type}, {"Disbursed Budget Riels PS", type number}, {"Disbursed $ Exchange Rate PS", type number}, {"Track_PWS Disburse 1", type text}, {"Track_PWS Disburse 2", type text}, {"Track_PWS Disburse 3", type text}, {"Track_PWS Disburse 4", type text}, {"Remain Budget Riels PS", type number}, {"Estimated Budget Riels PS", type any}, {"Balance Remained & Estimated Budget PS", type any}, {"Column2", type any}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ID", type text}, {"Year Stage", type text}, {"Proposal Type", type text}, {"Contract #", type text}, {"Initiator", type text}, {"Skill", type text}, {"Expected Date 1st", type date}, {"Text_Expected Date 1st", type date}, {"Date Doc Submit 1st", type date}, {"Date Approved 1st Doc", type date}, {"Date Received Budget 1st", type date}, {"Text Date Received Budget 1st", type date}, {"Disbursed 1 $", Currency.Type}, {"Expected Date 2nd", type date}, {"Text_Expected Date 2nd", type date}, {"Date Doc Submit 2nd", type date}, {"Date Approved 2nd Doc", type date}, {"Date Received Budget 2nd", type date}, {"Text Date Received Budget 2nd", type date}, {"Disbursed 2 $", Currency.Type}, {"Expected Date 3rd", type date}, {"Text_Expected Date 3rd", type date}, {"Date Doc Submit 3rd", type date}, {"Date Approved 3rd Doc", type date}, {"Date Received Budget 3rd", type date}, {"Text Date Received Budget 3rd", type date}, {"Disbursed 3 Riels", type number}, {"Disbursed 3 $", Currency.Type}, {"Planned Budget 4th#(lf)(20%)", type number}, {"Expected Date 4th", type date}, {"Text_Expected Date 4th", type date}, {"Date Doc Submit 4th", type date}, {"Date Approved 4th Doc", type date}, {"Date Received Budget 4th", type date}, {"Text Date Received Budget 4th", type date}, {"Disbursed 4 Riels", type number}, {"Disbursed 4 $", Currency.Type}, {"Disbursed $ Exchange Rate", Currency.Type}, {"%Disbursed", type number}, {"Budget Source", type text}, {"Focal M&E", type text}, {"Disbursed 4 Riels PS", type number}, {"Disbursed 4 $ PS", type number}, {"Estimated Budget Riels PS", type number}, {"Balance Remained & Estimated Budget PS", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Column2"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Removed Blank Rows", {{"Text_Expected Date 1st", type date}}, "id-ID"),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type with Locale", {{"Text_Expected Date 1st", null}}),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Replaced Errors", {{"Date Received Budget 1st", type date}}, "id-ID"),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Changed Type with Locale1", {{"Date Received Budget 1st", null}}),
				    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Replaced Errors1", {{"Text Date Received Budget 1st", type date}}, "id-ID"),
				    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Changed Type with Locale2", {{"Text Date Received Budget 1st", null}}),
				    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Replaced Errors2", {{"Text_Expected Date 2nd", null}}),
				    #"Replaced Errors4" = Table.ReplaceErrorValues(#"Replaced Errors3", {{"Text Date Received Budget 2nd", null}}),
				    #"Replaced Errors5" = Table.ReplaceErrorValues(#"Replaced Errors4", {{"Text_Expected Date 3rd", null}}),
				    #"Replaced Errors6" = Table.ReplaceErrorValues(#"Replaced Errors5", {{"Date Received Budget 3rd", null}}),
				    #"Replaced Errors7" = Table.ReplaceErrorValues(#"Replaced Errors6", {{"Text Date Received Budget 3rd", null}}),
				    #"Replaced Errors8" = Table.ReplaceErrorValues(#"Replaced Errors7", {{"Text_Expected Date 4th", null}}),
				    #"Replaced Errors9" = Table.ReplaceErrorValues(#"Replaced Errors8", {{"Date Received Budget 4th", null}}),
				    #"Replaced Errors10" = Table.ReplaceErrorValues(#"Replaced Errors9", {{"Text Date Received Budget 4th", null}}),
				    #"Replaced Errors11" = Table.ReplaceErrorValues(#"Replaced Errors10", {{"%Disbursed", null}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Errors11",{{"Estimated Budget Riels PS", type number}}),
				    #"Replaced Errors12" = Table.ReplaceErrorValues(#"Changed Type2", {{"Estimated Budget Riels PS", null}}),
				    #"Replaced Errors13" = Table.ReplaceErrorValues(#"Replaced Errors12", {{"Balance Remained & Estimated Budget PS", null}}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Replaced Errors13", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Blank Rows1",{"ID", "# Disbursements", "Disbursed 1 Riels", "Disbursed 1 $", "Disbursed 2 Riels", "Disbursed 2 $", "Disbursed 3 Riels", "Disbursed 3 $", "Disbursed 4 Riels", "Disbursed 4 $", "Disbursed 1 Riels PS", "Disbursed 1 $ PS", "Disbursed 2 Riels PS", "Disbursed 2 $ PS", "Disbursed 3 Riels PS", "Disbursed 3 $ PS", "Disbursed 4 Riels PS", "Disbursed 4 $ PS", "Disbursed Budget Riels PS", "Disbursed $ Exchange Rate PS", "Track_PWS Disburse 1", "Track_PWS Disburse 2", "Track_PWS Disburse 3", "Track_PWS Disburse 4", "Remain Budget Riels PS", "Estimated Budget Riels PS", "Balance Remained & Estimated Budget PS"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

