table Fact_KPI_Archieve
	lineageTag: c163a762-0d4c-4e79-b130-9c56b713378e

	column ID
		dataType: string
		lineageTag: 0433688b-2346-4e2d-9ec7-9d46fff255b4
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Attendance Report'
		dataType: int64
		formatString: 0
		lineageTag: a0e12bad-6db9-43db-bf32-651e86aee1aa
		summarizeBy: sum
		sourceColumn: Attendance Report

		annotation SummarizationSetBy = Automatic

	column 'Attendance Report F'
		dataType: double
		lineageTag: 83ecacff-2b6c-4b52-b98b-d334e7354f15
		summarizeBy: sum
		sourceColumn: Attendance Report F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Attendance Report Rate'
		dataType: double
		lineageTag: ab736474-fb73-43f1-b719-e0d055180674
		summarizeBy: sum
		sourceColumn: Attendance Report Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drop-out Report'
		dataType: double
		lineageTag: 612e8ca4-8003-4ea7-8b15-899afa631e52
		summarizeBy: sum
		sourceColumn: Drop-out Report

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drop-out Report F'
		dataType: double
		lineageTag: cb34c426-6f67-40b6-ba76-e837048a144c
		summarizeBy: sum
		sourceColumn: Drop-out Report F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Drop-out Report Rate'
		dataType: string
		lineageTag: a966c725-dc20-4f46-a473-9bbecc651579
		summarizeBy: none
		sourceColumn: Drop-out Report Rate

		annotation SummarizationSetBy = Automatic

	column 'Graduation Report'
		dataType: int64
		formatString: 0
		lineageTag: 4e8876f3-2571-4473-a93c-09ffd5b82f76
		summarizeBy: sum
		sourceColumn: Graduation Report

		annotation SummarizationSetBy = Automatic

	column 'Graduation Report F'
		dataType: double
		lineageTag: 5e2f41fb-c19c-4568-81dc-2e19467645a5
		summarizeBy: sum
		sourceColumn: Graduation Report F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Graduation Report Rate'
		dataType: string
		lineageTag: 15593711-87ac-477b-8482-110113a1d15a
		summarizeBy: none
		sourceColumn: Graduation Report Rate

		annotation SummarizationSetBy = Automatic

	column 'Employment Report'
		dataType: int64
		formatString: 0
		lineageTag: df7580e4-00d4-4ce3-8d3b-f8ee7758c13b
		summarizeBy: sum
		sourceColumn: Employment Report

		annotation SummarizationSetBy = Automatic

	column 'Employment Report F'
		dataType: int64
		formatString: 0
		lineageTag: 275f0d60-7229-4e84-8669-12fae631ea9f
		summarizeBy: sum
		sourceColumn: Employment Report F

		annotation SummarizationSetBy = Automatic

	column 'Employment Report Rate'
		dataType: string
		lineageTag: 937afd77-8623-4458-a274-f0ee8d4d52cf
		summarizeBy: none
		sourceColumn: Employment Report Rate

		annotation SummarizationSetBy = Automatic

	column 'Track_KPI Report'
		dataType: string
		lineageTag: 97145b6e-f126-4000-b898-febedf48c6a2
		summarizeBy: none
		sourceColumn: Track_KPI Report

		annotation SummarizationSetBy = Automatic

	column 'Satisfaction Report'
		dataType: double
		lineageTag: 13322c9d-023e-4d89-860b-2b67e2a6b351
		summarizeBy: sum
		sourceColumn: Satisfaction Report

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Satisfaction Report Rate'
		dataType: string
		lineageTag: cd5acfc4-54cf-4eb4-825d-1972e66c6716
		summarizeBy: none
		sourceColumn: Satisfaction Report Rate

		annotation SummarizationSetBy = Automatic

	column 'Budget Source'
		dataType: string
		lineageTag: d5bfe474-c2da-4f3d-99b7-c8b22e2aafb0
		summarizeBy: none
		sourceColumn: Budget Source

		annotation SummarizationSetBy = Automatic

	partition Fact_KPI_Archieve = m
		mode: import
		queryGroup: 'KPI Monitoring'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"3-KPI Monitoring_Sheet" = Source{[Item="3-KPI Monitoring",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"3-KPI Monitoring_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Contract #", type any}, {"Initiator", type any}, {"Skill Sector SOP", type any}, {"Proposal Type PS", type any}, {"Skill", type any}, {"Scheme", type any}, {"Training Type", type any}, {"Track_Contract Duration", type text}, {"Training Progress", type text}, {"Disbursement Progress", type text}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", type number}, {"Column2", Int64.Type}, {"Column1", type text}, {"Trainee Actual", Int64.Type}, {"Female Actual", Int64.Type}, {"Terminate", Int64.Type}, {"Dead", Int64.Type}, {"Resigned", Int64.Type}, {"Attendance Rate Commit", type number}, {"Drop-out (%) Commit", type number}, {"Graduation Rate Commit", type number}, {"Employment (%) Commit", type number}, {"Satisfaction Commit", type number}, {"Salary Commit $", Int64.Type}, {"%Salary Increase Commit", type number}, {"Track_KPI Commit", type text}, {"Attendance Report", Int64.Type}, {"Attendance Report F", Int64.Type}, {"Attendance Report Rate", type text}, {"Drop-out Report", Int64.Type}, {"Drop-out Report F", Int64.Type}, {"Drop-out Report Rate", type text}, {"Graduation Report", Int64.Type}, {"Graduation Report F", Int64.Type}, {"Graduation Report Rate", type text}, {"Employment Report", Int64.Type}, {"Employment Report F", Int64.Type}, {"Employment Report Rate", type text}, {"Track_KPI Report", type text}, {"Satisfaction Report", type number}, {"Satisfaction Report Rate", type text}, {"Attendance Rate Actual", type any}, {"Attendance Rate Actual Result", type text}, {"Drop-out (%) Actual", type number}, {"Drop-out Actual Result", type text}, {"Graduation % Actual", type number}, {"Graduation (%) Actual Result", type text}, {"Employment (%) Actual", type number}, {"Emaployment (%) Actual Result", type text}, {"Salary Actual", Int64.Type}, {"Salary Actual Result", type text}, {"% Salary Increase Actual", type number}, {"% Salary Increase Actual Result", type text}, {"Track_KPI Actual", type text}, {"Tracer Study", type text}, {"Track_Feeback", type text}, {"Budget Source", type any}, {"Focal M&E", type any}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ID", type text}, {"Contract #", type text}, {"Initiator", type text}, {"Skill Sector SOP", type text}, {"Proposal Type PS", type text}, {"Skill", type text}, {"Scheme", type text}, {"Training Type", type text}, {"Track_Contract Duration", type text}, {"Female_Proposal", Int64.Type}, {"Salary Commit $", Currency.Type}, {"Attendance Report Rate", type number}, {"Attendance Report F", type number}, {"Drop-out Report", type number}, {"Drop-out Report F", type number}, {"Graduation Report F", type number}, {"Attendance Rate Actual", type number}, {"Attendance Rate Actual Result", type number}, {"Drop-out (%) Actual", type number}, {"Drop-out Actual Result", type text}, {"Graduation (%) Actual Result", type text}, {"Salary Actual", type number}, {"Budget Source", type text}, {"Focal M&E", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"ID", "Year", "Contract #", "Initiator", "Skill Sector SOP", "Proposal Type PS", "Skill", "Scheme", "Training Type", "Track_Contract Duration", "Training Progress", "Disbursement Progress", "Trainees_Proposal", "Female_Proposal", "Column2", "Column1", "Trainee Actual", "Female Actual", "Terminate", "Dead", "Resigned", "Attendance Rate Commit", "Drop-out (%) Commit", "Graduation Rate Commit", "Employment (%) Commit", "Satisfaction Commit", "Salary Commit $", "%Salary Increase Commit", "Track_KPI Commit", "Attendance Report", "Attendance Report F", "Attendance Report Rate", "Drop-out Report", "Drop-out Report F", "Drop-out Report Rate", "Graduation Report", "Graduation Report F", "Graduation Report Rate", "Employment Report", "Employment Report F", "Employment Report Rate", "Track_KPI Report", "Satisfaction Report", "Satisfaction Report Rate", "Attendance Rate Actual", "Attendance Rate Actual Result", "Drop-out (%) Actual", "Drop-out Actual Result", "Graduation % Actual", "Graduation (%) Actual Result", "Employment (%) Actual", "Emaployment (%) Actual Result", "Salary Actual", "Salary Actual Result", "% Salary Increase Actual", "% Salary Increase Actual Result", "Track_KPI Actual", "Tracer Study", "Track_Feeback", "Budget Source", "Focal M&E"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Blank Rows"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Duplicates",{"ID", "Attendance Report", "Attendance Report F", "Attendance Report Rate", "Drop-out Report", "Drop-out Report F", "Drop-out Report Rate", "Graduation Report", "Graduation Report F", "Graduation Report Rate", "Employment Report", "Employment Report F", "Employment Report Rate", "Track_KPI Report", "Satisfaction Report", "Satisfaction Report Rate", "Budget Source"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

