table Fact_Proposal_Cost_PMS_Append
	lineageTag: ab2e4f9e-7b15-47f2-9581-c3c65fdab424

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 9c8752bd-7027-43ba-bab7-96aa6d81bb02
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Trainees_Proposal
		dataType: int64
		formatString: 0
		lineageTag: 534c21d9-0a40-44f2-bb6f-fd052f489c00
		summarizeBy: sum
		sourceColumn: Trainees_Proposal

		annotation SummarizationSetBy = Automatic

	column 'Total Cost'
		dataType: double
		lineageTag: 151987be-c62e-4ca5-aeb8-c908fc48b5f2
		summarizeBy: sum
		sourceColumn: Total Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SDF Cost'
		dataType: double
		lineageTag: 5e269e2b-5ad3-4164-80e6-ba6c510a253f
		summarizeBy: sum
		sourceColumn: SDF Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SDF Cost (%)'
		dataType: double
		lineageTag: cf1659f5-6d2d-4fb3-a24e-559f39f53b25
		summarizeBy: sum
		sourceColumn: SDF Cost (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Training Provider Cost'
		dataType: double
		lineageTag: 7b18b1f8-76ef-4d1e-8c0e-3dc5978d9ab0
		summarizeBy: sum
		sourceColumn: Training Provider Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Training Provider Cost (%)'
		dataType: double
		lineageTag: ce1c2ed5-7011-4cd4-a543-c77a83fa3525
		summarizeBy: sum
		sourceColumn: Training Provider Cost (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Enterprise Cost'
		dataType: double
		lineageTag: 2ed677b2-08d6-4096-80d8-2c6056ad7d2f
		summarizeBy: sum
		sourceColumn: Enterprise Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Enterprise Cost (%)'
		dataType: double
		lineageTag: 12375431-c5ca-4e47-9df6-2c8306d79bf9
		summarizeBy: sum
		sourceColumn: Enterprise Cost (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unified_ID
		dataType: string
		lineageTag: b293872e-14e8-4e15-ba19-4e56e462b92c
		summarizeBy: none
		sourceColumn: Unified_ID

		annotation SummarizationSetBy = Automatic

	column New_ID
		dataType: string
		lineageTag: 4c4e2457-cf02-47e3-8ce3-dcb6dffc2659
		summarizeBy: none
		sourceColumn: New_ID

		annotation SummarizationSetBy = Automatic

	column Female_Proposal
		dataType: int64
		formatString: 0
		lineageTag: a47062dc-3b82-44d2-8d73-b0e53eeffbd1
		summarizeBy: sum
		sourceColumn: Female_Proposal

		annotation SummarizationSetBy = Automatic

	partition Fact_Proposal_Cost_PMS_Append = m
		mode: import
		queryGroup: 'Proposal\PMS_Proposals\PMS_Data Source'
		source =
				let
				    Source = Fact_Proposal_Cost_PMS,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Total Trainee", "Total Trainee Allowance", "Total Trainining Cost", "Total Cost", "SDF Cost", "SDF Cost (%)", "Training Provider Cost", "Training Provider Cost (%)", "Enterprise Cost", "Enterprise Cost (%)", "Unified_ID", "New_ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"Total Trainee", "Trainees_Proposal"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Unified_ID"}, Dim_Trainees​​_Proposal_Master, {"Unified_ID"}, "Dim_Trainees​​_Proposal_Master", JoinKind.LeftOuter),
				    #"Expanded Dim_Trainees​​_Proposal_Master" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Trainees​​_Proposal_Master", {"Trainees_Proposal", "Female_Proposal"}, {"Dim_Trainees​​_Proposal_Master.Trainees_Proposal", "Dim_Trainees​​_Proposal_Master.Female_Proposal"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim_Trainees​​_Proposal_Master",{"Dim_Trainees​​_Proposal_Master.Trainees_Proposal"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Dim_Trainees​​_Proposal_Master.Female_Proposal", "Female_Proposal"}}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1",{"ID", "Trainees_Proposal", "Total Cost", "SDF Cost", "SDF Cost (%)", "Training Provider Cost", "Training Provider Cost (%)", "Enterprise Cost", "Enterprise Cost (%)", "Unified_ID", "New_ID", "Female_Proposal"})
				in
				    #"Removed Other Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

