table 'PROGRESS PERFORMANCE TRACKING SHEET  (2_ElapeTime)'
	lineageTag: 9082f0e1-ce23-488f-a47a-75e470b35218

	column DESCRIPTION
		dataType: string
		lineageTag: f2ac8be4-3b49-4dc5-9af8-c77265393154
		summarizeBy: none
		sourceColumn: DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column 'QUANTITATIVE (#)'
		dataType: string
		lineageTag: e1ec229b-42ce-49a9-871d-127888fe7f76
		summarizeBy: none
		sourceColumn: QUANTITATIVE (#)

		annotation SummarizationSetBy = Automatic

	column 'QUALITATIVE (%)'
		dataType: double
		lineageTag: ca89fa47-9d24-4b6c-a2c7-41c1b21215a0
		summarizeBy: sum
		sourceColumn: QUALITATIVE (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REMARK
		dataType: string
		lineageTag: 76e4d560-5127-4249-9aad-0cd4027ba7ad
		summarizeBy: none
		sourceColumn: REMARK

		annotation SummarizationSetBy = Automatic

	partition 'PROGRESS PERFORMANCE TRACKING SHEET  (2_ElapeTime)' = m
		mode: import
		queryGroup: 'SBJ Project'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SBJ_SDF_Enhanced_Rating_System_V2.xlsx"), null, false),
				    #"2_ElapeTime_sheet" = Source{[Item="2_ElapeTime",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Removed Top Rows" = Table.Skip(#"2_ElapeTime_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"QUANTITATIVE (#)", type text}, {"QUALITATIVE (%)", type number}, {"DESCRIPTION", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

