table 'Progress Monitoring'
	lineageTag: 0e5a47d1-ee2c-4d17-a2b9-b90d127ef204

	column ID
		dataType: string
		lineageTag: 4f8c6221-3a14-40c4-9f2f-abf8214b4fbb
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a61bd842-23f7-4e88-829a-c3b1186011ff
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Stage'
		dataType: string
		lineageTag: deb29305-4841-4fa6-bcd2-6079599b9883
		summarizeBy: none
		sourceColumn: Year Stage

		annotation SummarizationSetBy = Automatic

	column 'Proposal Type'
		dataType: string
		lineageTag: 3961af34-19b8-4224-92ba-8fb657137583
		summarizeBy: none
		sourceColumn: Proposal Type

		annotation SummarizationSetBy = Automatic

	column 'Proposal Type PS'
		dataType: string
		lineageTag: e731cd36-a5f2-4ce7-9e37-3f06c475132c
		summarizeBy: none
		sourceColumn: Proposal Type PS

		annotation SummarizationSetBy = Automatic

	column Initiator
		dataType: string
		lineageTag: cf25e4e6-0061-44e0-a4a7-6239cc26e7e8
		summarizeBy: none
		sourceColumn: Initiator

		annotation SummarizationSetBy = Automatic

	column Skill
		dataType: string
		lineageTag: 1687f09d-dc79-4adc-8ec7-45d87de0a506
		summarizeBy: none
		sourceColumn: Skill

		annotation SummarizationSetBy = Automatic

	column 'Training Type'
		dataType: string
		lineageTag: d865cac8-ddfa-4028-9b27-267d8aa01caf
		summarizeBy: none
		sourceColumn: Training Type

		annotation SummarizationSetBy = Automatic

	column Trainees_Proposal
		dataType: int64
		formatString: 0
		lineageTag: cf66a1a8-69a8-47af-88cc-04f854233629
		summarizeBy: sum
		sourceColumn: Trainees_Proposal

		annotation SummarizationSetBy = Automatic

	column Female_Proposal
		dataType: int64
		formatString: 0
		lineageTag: d1565807-77b2-4aab-9e32-14393e26ef5e
		summarizeBy: sum
		sourceColumn: Female_Proposal

		annotation SummarizationSetBy = Automatic

	column 'SDF Contribution Riels'
		dataType: double
		lineageTag: b926c715-1f0c-4f27-97fb-4a62ab5cdec2
		summarizeBy: sum
		sourceColumn: SDF Contribution Riels

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SDF Contribution $'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 95b819ba-c71b-4956-9f4b-2bdb6ea143ca
		summarizeBy: sum
		sourceColumn: SDF Contribution $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Date Approved'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f133c0e-f206-4e54-8f27-1fc5d16924e0
		summarizeBy: none
		sourceColumn: Date Approved

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Text Date Approved'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1aceb6fc-1d07-4263-a8f9-dde4ac0c4019
		summarizeBy: none
		sourceColumn: Text Date Approved

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Contract #'
		dataType: string
		lineageTag: 812bb09b-de0f-437a-929a-8adf0690691a
		summarizeBy: none
		sourceColumn: Contract #

		annotation SummarizationSetBy = Automatic

	column 'Date_Draft Contract'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cb74c3d-491c-4e38-8be8-11a6a2010a98
		summarizeBy: none
		sourceColumn: Date_Draft Contract

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date_Applicant Completed'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5929535c-ac77-4c98-b1a5-de56aec4a18d
		summarizeBy: none
		sourceColumn: Date_Applicant Completed

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date_Finance Completed'
		dataType: dateTime
		formatString: Long Date
		lineageTag: edeb4bcb-c765-44be-9ee6-8a81091e05f1
		summarizeBy: none
		sourceColumn: Date_Finance Completed

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date_M&E Completed'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ba90cbe-1bd7-4263-9968-71dad8fdea4d
		summarizeBy: none
		sourceColumn: Date_M&E Completed

		annotation SummarizationSetBy = Automatic

	column 'Date_Assistant Completed'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cedb9000-a546-47d0-8597-5e1b95c696e8
		summarizeBy: none
		sourceColumn: Date_Assistant Completed

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date_To Amin'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5617005f-bdc2-4c7d-989a-a86fd31c80dd
		summarizeBy: none
		sourceColumn: Date_To Amin

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date_Admin Out'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3fdfa7cc-ae71-4426-b133-e3b61847c4d3
		summarizeBy: none
		sourceColumn: Date_Admin Out

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Track_Review Process'
		dataType: string
		lineageTag: 71b7b492-d456-4241-a958-e1ced21090b2
		summarizeBy: none
		sourceColumn: Track_Review Process

		annotation SummarizationSetBy = Automatic

	column 'Contract Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c682f663-481d-4b58-80cb-6c4bc989bd6d
		summarizeBy: none
		sourceColumn: Contract Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ContractValid Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 46c7a64f-5c9a-4bad-bc5a-41f4c003dd56
		summarizeBy: none
		sourceColumn: ContractValid Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Contract Duration'
		dataType: int64
		formatString: 0
		lineageTag: 79b6dff8-1677-4093-8cba-1c63c46c9f1f
		summarizeBy: sum
		sourceColumn: Contract Duration

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 984935f1-1b06-40ff-9f28-b3d4ac8710af
		summarizeBy: none
		sourceColumn: Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bbd34729-c2d6-4a7d-9a21-0958b6e7712b
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End Date in Contract'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9be83b1-922d-4d2e-8303-95da03c9160a
		summarizeBy: none
		sourceColumn: End Date in Contract

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Terminated Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 65527fc2-6839-4df6-8e2a-57bd611cd623
		summarizeBy: none
		sourceColumn: Terminated Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Track_Contract Duration'
		dataType: string
		lineageTag: 4bf30ee9-09ed-4b83-898d-19e5a8a48a5c
		summarizeBy: none
		sourceColumn: Track_Contract Duration

		annotation SummarizationSetBy = Automatic

	column 'Track_Progress Sheet'
		dataType: string
		lineageTag: 8a1b1706-13d5-453b-8198-93f6ce3e3fba
		summarizeBy: none
		sourceColumn: Track_Progress Sheet

		annotation SummarizationSetBy = Automatic

	column 'Training Progress'
		dataType: string
		lineageTag: 49eda694-19d8-4fdc-82d6-05df05e97eff
		summarizeBy: none
		sourceColumn: Training Progress

		annotation SummarizationSetBy = Automatic

	column 'Disbursement Progress'
		dataType: string
		lineageTag: bb778528-ebc1-431e-b307-6f0151fed58b
		summarizeBy: none
		sourceColumn: Disbursement Progress

		annotation SummarizationSetBy = Automatic

	column '#Trainee Training'
		dataType: int64
		formatString: 0
		lineageTag: ebc04473-8e46-4aba-806a-249a4efc71ef
		summarizeBy: sum
		sourceColumn: #Trainee Training

		annotation SummarizationSetBy = Automatic

	column '#Trainee Training Female'
		dataType: int64
		formatString: 0
		lineageTag: 5df7f951-2d2d-4c36-b3e1-554026c5341e
		summarizeBy: sum
		sourceColumn: #Trainee Training Female

		annotation SummarizationSetBy = Automatic

	column '#Trainee Completed'
		dataType: int64
		formatString: 0
		lineageTag: c2db01d2-0bdc-464b-87cc-05bd1d6a1bc1
		summarizeBy: sum
		sourceColumn: #Trainee Completed

		annotation SummarizationSetBy = Automatic

	column '#Trainee Completed Female'
		dataType: int64
		formatString: 0
		lineageTag: ca03f204-e4b9-47b9-b9ea-47e22346456b
		summarizeBy: sum
		sourceColumn: #Trainee Completed Female

		annotation SummarizationSetBy = Automatic

	column 'Orientation Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4897b0cc-5af6-440f-b203-2442690e9235
		summarizeBy: none
		sourceColumn: Orientation Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column '1st Visit'
		dataType: string
		lineageTag: 58ab0451-499c-4d31-b0cc-cf235b7c89fe
		summarizeBy: none
		sourceColumn: 1st Visit

		annotation SummarizationSetBy = Automatic

	column '2nd Visit'
		dataType: string
		lineageTag: 6541dd8f-0f3d-4fa2-a851-3726f8f3f6d3
		summarizeBy: none
		sourceColumn: 2nd Visit

		annotation SummarizationSetBy = Automatic

	column 'Budget Source'
		dataType: string
		lineageTag: f0a60e87-ccac-4a66-a97c-75c146aaed83
		summarizeBy: none
		sourceColumn: Budget Source

		annotation SummarizationSetBy = Automatic

	column 'Focal M&E'
		dataType: string
		lineageTag: 143be1d0-9e9a-452f-b643-ada409236a7a
		summarizeBy: none
		sourceColumn: Focal M&E

		annotation SummarizationSetBy = Automatic

	column 'Tracer study'
		dataType: string
		lineageTag: 72b30fb7-2626-4995-907f-c6a146cc6451
		summarizeBy: none
		sourceColumn: Tracer study

		annotation SummarizationSetBy = Automatic

	column Track_Trainee
		dataType: string
		lineageTag: 2b812684-86c1-4691-9ec1-817cc8220789
		summarizeBy: none
		sourceColumn: Track_Trainee

		annotation SummarizationSetBy = Automatic

	column Track_Feeback
		dataType: string
		lineageTag: 364fea6f-86e1-421f-a112-e4c6a4a886b0
		summarizeBy: none
		sourceColumn: Track_Feeback

		annotation SummarizationSetBy = Automatic

	partition 'Progress Monitoring' = m
		mode: import
		queryGroup: 'Progress Monitoring'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\SDF_DATABASE_BACKUP_20251116.xlsx"), null, true),
				    #"2-Progress Monitoring_Sheet" = Source{[Item="2-Progress Monitoring",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"2-Progress Monitoring_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Year", Int64.Type}, {"Year Stage", type any}, {"Proposal Type", type any}, {"Proposal Type PS", type any}, {"Initiator", type any}, {"Skill", type any}, {"Training Type", type any}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", type number}, {"SDF Contribution Riels", type number}, {"SDF Contribution $", type number}, {"Date Approved", Int64.Type}, {"Text Date Approved", type date}, {"Contract #", type text}, {"Date_Draft Contract", type any}, {"Date_Applicant Completed", type any}, {"Date_Finance Completed", type any}, {"Date_M&E Completed", type any}, {"Date_Assistant Completed", type any}, {"Date_To Amin", type any}, {"Date_Admin Out", type any}, {"Track_Review Process", type text}, {"Contract Date", Int64.Type}, {"ContractValid Date", Int64.Type}, {"Contract Duration", Int64.Type}, {"Start Date", Int64.Type}, {"End Date", Int64.Type}, {"End Date in Contract", Int64.Type}, {"Terminated Date", Int64.Type}, {"Track_Contract Duration", type text}, {"Track_Progress Sheet", type text}, {"Training Progress", type text}, {"Disbursement Progress", type text}, {"#Trainee Training", Int64.Type}, {"#Trainee Training Female", Int64.Type}, {"#Trainee Completed", Int64.Type}, {"#Trainee Completed Female", Int64.Type}, {"Orientation Date", type any}, {"1st Visit", Int64.Type}, {"2nd Visit", type any}, {"Budget Source", type any}, {"Focal M&E", type text}, {"Tracer study", type text}, {"Track_Trainee", type any}, {"Track_Feeback", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"ID", type text}, {"Year Stage", type text}, {"Proposal Type", type text}, {"Proposal Type PS", type text}, {"Initiator", type text}, {"Skill", type text}, {"Training Type", type text}, {"Trainees_Proposal", Int64.Type}, {"Female_Proposal", Int64.Type}, {"SDF Contribution $", Currency.Type}, {"Date Approved", type date}, {"Date_Draft Contract", type date}, {"Date_Applicant Completed", type date}, {"Date_Finance Completed", type date}, {"Date_M&E Completed", type datetime}, {"Date_Assistant Completed", type date}, {"Date_To Amin", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"Date_To Amin", type date}, {"Date_Admin Out", type date}, {"Contract Date", type date}, {"ContractValid Date", type date}, {"Start Date", type date}, {"End Date", type date}, {"End Date in Contract", type date}, {"Terminated Date", type date}, {"Orientation Date", type date}, {"1st Visit", type text}, {"2nd Visit", type text}, {"Budget Source", type text}, {"Track_Trainee", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type2", {"ID", "Year", "Year Stage", "Proposal Type", "Proposal Type PS", "Initiator", "Skill", "Training Type", "Trainees_Proposal", "Female_Proposal", "SDF Contribution Riels", "SDF Contribution $", "Date Approved", "Text Date Approved", "Contract #", "Date_Draft Contract", "Date_Applicant Completed", "Date_Finance Completed", "Date_M&E Completed", "Date_Assistant Completed", "Date_To Amin", "Date_Admin Out", "Track_Review Process", "Contract Date", "ContractValid Date", "Contract Duration", "Start Date", "End Date", "End Date in Contract", "Terminated Date", "Track_Contract Duration", "Track_Progress Sheet", "Training Progress", "Disbursement Progress", "#Trainee Training", "#Trainee Training Female", "#Trainee Completed", "#Trainee Completed Female", "Orientation Date", "1st Visit", "2nd Visit", "Budget Source", "Focal M&E", "Tracer study", "Track_Trainee", "Track_Feeback"}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Errors", {"ID", "Year", "Year Stage", "Proposal Type", "Proposal Type PS", "Initiator", "Skill", "Training Type", "Trainees_Proposal", "Female_Proposal", "SDF Contribution Riels", "SDF Contribution $", "Date Approved", "Text Date Approved", "Contract #", "Date_Draft Contract", "Date_Applicant Completed", "Date_Finance Completed", "Date_M&E Completed", "Date_Assistant Completed", "Date_To Amin", "Date_Admin Out", "Track_Review Process", "Contract Date", "ContractValid Date", "Contract Duration", "Start Date", "End Date", "End Date in Contract", "Terminated Date", "Track_Contract Duration", "Track_Progress Sheet", "Training Progress", "Disbursement Progress", "#Trainee Training", "#Trainee Training Female", "#Trainee Completed", "#Trainee Completed Female", "Orientation Date", "1st Visit", "2nd Visit", "Budget Source", "Focal M&E", "Tracer study", "Track_Trainee", "Track_Feeback"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

