table 'Traineess'' Satisfaction_KOBO'
	lineageTag: 6ab4a81e-7b80-47f9-aa11-eadf94157143

	column intro_text
		dataType: string
		lineageTag: 85db4895-7378-4102-9357-583f651c57f0
		summarizeBy: none
		sourceColumn: intro_text

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: string
		lineageTag: 1484bacf-94bb-4b76-9b7b-385b258e778e
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: string
		lineageTag: 8881c64d-4607-4d3f-af45-235d4c078eb6
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column org
		dataType: string
		lineageTag: 2171d316-f58a-47db-8161-610750fd7d98
		summarizeBy: none
		sourceColumn: org

		annotation SummarizationSetBy = Automatic

	column If_other_specify
		dataType: string
		lineageTag: 963246a8-3df1-4e4d-a16a-6ea1a0edb995
		summarizeBy: none
		sourceColumn: If_other_specify

		annotation SummarizationSetBy = Automatic

	column fund
		dataType: string
		lineageTag: 431b8d25-0c36-4833-9a8d-8b2a3738b328
		summarizeBy: none
		sourceColumn: fund

		annotation SummarizationSetBy = Automatic

	column contract_No
		dataType: string
		lineageTag: dc8e78c4-ee04-4d73-bb29-5cb4296f0c1f
		summarizeBy: none
		sourceColumn: contract_No

		annotation SummarizationSetBy = Automatic

	column feedback_date
		dataType: string
		lineageTag: 9c468d6e-a970-4e4a-bd72-bed04ca98560
		summarizeBy: none
		sourceColumn: feedback_date

		annotation SummarizationSetBy = Automatic

	column provider
		dataType: string
		lineageTag: e3aff482-f54d-4200-9b83-1c7f3e731634
		summarizeBy: none
		sourceColumn: provider

		annotation SummarizationSetBy = Automatic

	column other_tp_name
		dataType: string
		lineageTag: cc2f1aaa-afd8-41c3-ab63-207f809b5784
		summarizeBy: none
		sourceColumn: other_tp_name

		annotation SummarizationSetBy = Automatic

	column course
		dataType: string
		lineageTag: 5910ec47-30f6-47e6-87b8-d976b66687a9
		summarizeBy: none
		sourceColumn: course

		annotation SummarizationSetBy = Automatic

	column Choose_Type_of_Training
		dataType: string
		lineageTag: e1c529cb-224c-411c-a103-d0cc9b03799f
		summarizeBy: none
		sourceColumn: Choose_Type_of_Training

		annotation SummarizationSetBy = Automatic

	column Trainee_Name
		dataType: string
		lineageTag: d952eb9e-4964-4b73-904f-10d74d6245e4
		summarizeBy: none
		sourceColumn: Trainee_Name

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 86217290-bfe4-4a16-8f4a-540938e9fb2d
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column program_type
		dataType: string
		lineageTag: b4c442fe-afac-404d-814a-837a5bc8c5f7
		summarizeBy: none
		sourceColumn: program_type

		annotation SummarizationSetBy = Automatic

	column batch_number
		dataType: string
		lineageTag: eded31da-79d0-4d82-b203-e9e2262d541a
		summarizeBy: none
		sourceColumn: batch_number

		annotation SummarizationSetBy = Automatic

	column rating_note
		dataType: string
		lineageTag: 8a837cc4-da43-4931-a92f-6febbfa5f30d
		summarizeBy: none
		sourceColumn: rating_note

		annotation SummarizationSetBy = Automatic

	column q1_1
		dataType: double
		lineageTag: ccad2b5c-8b37-4a22-a5db-d6e27067f305
		summarizeBy: sum
		sourceColumn: q1_1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_1_explain
		dataType: string
		lineageTag: 6345f308-c3eb-4b1e-b1b1-eaf1bec4d0a0
		summarizeBy: none
		sourceColumn: q1_1_explain

		annotation SummarizationSetBy = Automatic

	column q1_2
		dataType: double
		lineageTag: 0217c981-4835-4b95-be35-2606dd2c5922
		summarizeBy: sum
		sourceColumn: q1_2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_2_explain
		dataType: string
		lineageTag: ba6092ec-2872-497e-893c-e06130bcae67
		summarizeBy: none
		sourceColumn: q1_2_explain

		annotation SummarizationSetBy = Automatic

	column q1_3
		dataType: double
		lineageTag: f1b2d181-762d-4f27-a3b3-32c046baf3cc
		summarizeBy: sum
		sourceColumn: q1_3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_3_explain
		dataType: string
		lineageTag: 27d83d6a-9af7-42b2-b6b4-64fa94ca5709
		summarizeBy: none
		sourceColumn: q1_3_explain

		annotation SummarizationSetBy = Automatic

	column q1_4
		dataType: double
		lineageTag: 23737f93-5547-41bf-b237-5f050afe4509
		summarizeBy: sum
		sourceColumn: q1_4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_4_explain
		dataType: string
		lineageTag: 60afd81f-1d68-4fbd-9ec9-e99675132c73
		summarizeBy: none
		sourceColumn: q1_4_explain

		annotation SummarizationSetBy = Automatic

	column q1_5
		dataType: double
		lineageTag: 25c229cd-30a5-40e6-8ba4-a47dc5bcdbd7
		summarizeBy: sum
		sourceColumn: q1_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_5_explain
		dataType: string
		lineageTag: 61652a33-ea07-471d-bdf0-2bdaa4009180
		summarizeBy: none
		sourceColumn: q1_5_explain

		annotation SummarizationSetBy = Automatic

	column q1_6
		dataType: double
		lineageTag: 549a3d68-da4c-4357-a5b0-c2284c6a6dd4
		summarizeBy: sum
		sourceColumn: q1_6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_6_explain
		dataType: string
		lineageTag: 19d0f10f-2f8a-4d3a-81ea-a2b5900617a5
		summarizeBy: none
		sourceColumn: q1_6_explain

		annotation SummarizationSetBy = Automatic

	column q1_7
		dataType: double
		lineageTag: 5a1fa0f7-de0b-4099-a902-3ae866ba8f81
		summarizeBy: sum
		sourceColumn: q1_7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_7_explain
		dataType: string
		lineageTag: 9987a0bd-92b3-42b7-b525-b60ffd57413c
		summarizeBy: none
		sourceColumn: q1_7_explain

		annotation SummarizationSetBy = Automatic

	column q1_8
		dataType: double
		lineageTag: 56155aa2-2530-4bcc-97b6-ea04f24ba575
		summarizeBy: sum
		sourceColumn: q1_8

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_8_explain
		dataType: string
		lineageTag: a5bd78c5-7545-4e5f-a33e-c936b292c172
		summarizeBy: none
		sourceColumn: q1_8_explain

		annotation SummarizationSetBy = Automatic

	column q1_9
		dataType: double
		lineageTag: 99a2b4d2-6db6-406d-bf64-7ab5b5a598ce
		summarizeBy: sum
		sourceColumn: q1_9

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q1_9_explain
		dataType: string
		lineageTag: d9b18541-559b-42c5-b0e9-b5994e3532df
		summarizeBy: none
		sourceColumn: q1_9_explain

		annotation SummarizationSetBy = Automatic

	column overall_score
		dataType: double
		lineageTag: 004cbee7-3eda-4884-8ba8-ec37c9118505
		summarizeBy: sum
		sourceColumn: overall_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overall_score_decimal
		dataType: double
		lineageTag: 97f1cf2c-e9a7-45ee-b876-ea4d74b5757d
		summarizeBy: sum
		sourceColumn: overall_score_decimal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overall_display
		dataType: string
		lineageTag: 4f76ef0b-0492-4573-b435-3d67114475ce
		summarizeBy: none
		sourceColumn: overall_display

		annotation SummarizationSetBy = Automatic

	column q2_1
		dataType: string
		lineageTag: b40e448e-09ba-4221-8ba6-1ee3cd0f5967
		summarizeBy: none
		sourceColumn: q2_1

		annotation SummarizationSetBy = Automatic

	column q2_1_specify
		dataType: string
		lineageTag: 18d12f15-cec0-477a-b0cc-d150847db16d
		summarizeBy: none
		sourceColumn: q2_1_specify

		annotation SummarizationSetBy = Automatic

	column q2_2
		dataType: string
		lineageTag: 246b7787-babd-4be0-be2e-58f057203904
		summarizeBy: none
		sourceColumn: q2_2

		annotation SummarizationSetBy = Automatic

	column thank_you
		dataType: string
		lineageTag: e55a29bb-6c63-4e9c-9785-92071801051a
		summarizeBy: none
		sourceColumn: thank_you

		annotation SummarizationSetBy = Automatic

	column start
		dataType: string
		lineageTag: 675f56d2-52b1-42cd-bf9c-45529f7b891a
		summarizeBy: none
		sourceColumn: start

		annotation SummarizationSetBy = Automatic

	column today
		dataType: string
		lineageTag: 583f4f26-4839-447a-be38-7d0a45b0b681
		summarizeBy: none
		sourceColumn: today

		annotation SummarizationSetBy = Automatic

	column deviceid
		dataType: string
		lineageTag: e3accb25-14dc-40a6-a6e9-45dcd48bf1a4
		summarizeBy: none
		sourceColumn: deviceid

		annotation SummarizationSetBy = Automatic

	column _id
		dataType: string
		lineageTag: 359610d5-9c20-42bc-b74b-9d611323bd08
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column _uuid
		dataType: string
		lineageTag: 3ac7f3d7-da39-4250-acdc-da471f24fd46
		summarizeBy: none
		sourceColumn: _uuid

		annotation SummarizationSetBy = Automatic

	column _submission_time
		dataType: string
		lineageTag: ac4d44cf-1d27-416d-9b15-16651bc8c470
		summarizeBy: none
		sourceColumn: _submission_time

		annotation SummarizationSetBy = Automatic

	column _validation_status
		dataType: string
		lineageTag: a91d6cdb-9767-45db-9d83-8116b96597a8
		summarizeBy: none
		sourceColumn: _validation_status

		annotation SummarizationSetBy = Automatic

	column _notes
		dataType: string
		lineageTag: 2b1dad21-2fb1-422a-a672-a98817dc1ad5
		summarizeBy: none
		sourceColumn: _notes

		annotation SummarizationSetBy = Automatic

	column _status
		dataType: string
		lineageTag: 66ee9ed2-b2b5-45fa-ab19-a7f27ddf145f
		summarizeBy: none
		sourceColumn: _status

		annotation SummarizationSetBy = Automatic

	column _submitted_by
		dataType: string
		lineageTag: 051b301b-3b95-4c21-84ca-dd912af1d91e
		summarizeBy: none
		sourceColumn: _submitted_by

		annotation SummarizationSetBy = Automatic

	column __version__
		dataType: string
		lineageTag: 1e1c8b7b-a923-4dd8-a84d-bb6e777b8693
		summarizeBy: none
		sourceColumn: __version__

		annotation SummarizationSetBy = Automatic

	column _tags
		dataType: string
		lineageTag: bf8cb0ef-d9ad-4f08-92d0-e1be474e2b4a
		summarizeBy: none
		sourceColumn: _tags

		annotation SummarizationSetBy = Automatic

	column meta/rootUuid
		dataType: string
		lineageTag: 23bc4652-46a2-4d0f-870d-7a29590c64af
		summarizeBy: none
		sourceColumn: meta/rootUuid

		annotation SummarizationSetBy = Automatic

	column _index
		dataType: string
		lineageTag: f5d90d00-43a8-4839-a636-76c39342eefc
		summarizeBy: none
		sourceColumn: _index

		annotation SummarizationSetBy = Automatic

	partition 'Traineess'' Satisfaction_KOBO' = m
		mode: import
		queryGroup: 'Trainees'' Satisfaction_KOBO'
		source =
				let
				    Source = Csv.Document(Web.Contents("https://kf.kobotoolbox.org/api/v2/assets/azRmjXmFEJ2QoFnFcEHMML/export-settings/esWg6hvft4DeMa2vHDvZxqG/data.csv"),[Delimiter=";", Columns=56, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"q1_1", type number}, {"q1_2", type number}, {"q1_3", type number}, {"q1_4", type number}, {"q1_5", type number}, {"q1_6", type number}, {"q1_7", type number}, {"q1_8", type number}, {"q1_9", type number}, {"overall_score", type number}, {"overall_score_decimal", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

