table 'Training Provider List_Final'
	lineageTag: 6b69e702-1e5e-43c6-a104-228e988c6679

	column 'Training Provider'
		dataType: string
		lineageTag: 73fef937-a00b-436b-8af0-1e5e7acb6f04
		summarizeBy: none
		sourceColumn: Training Provider

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: c5862fba-de4d-48fa-a867-ea57b32f399a
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Grouped Training Provider'
		dataType: string
		lineageTag: 4a9634c3-86c1-4966-95cb-5172a193918c
		summarizeBy: none
		sourceColumn: Grouped Training Provider

		annotation SummarizationSetBy = Automatic

	column Acronym
		dataType: string
		lineageTag: 0198065d-c9e3-4b51-b6a6-2e09ced947e0
		summarizeBy: none
		sourceColumn: Acronym

		annotation SummarizationSetBy = Automatic

	partition 'Training Provider List_Final' = m
		mode: import
		queryGroup: 'Progress Monitoring'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\U-ser\OneDrive - sdfcambodia.org\BackUp_SDF_PBI_database_Sep2025\TPGroupCleaned_Final.xlsx"), null, true),
				    #"Training Provider List_Sheet" = Source{[Item="Training Provider List",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Training Provider List_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Acronym", type text}, {"Grouped Training Provider", type text}, {"Training Provider", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,"Other",Replacer.ReplaceValue,{"Acronym"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Index", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type1", {"Acronym"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Training Provider", "Grouped Training Provider", "Acronym", "Index"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Reordered Columns","N","Other",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","BA","BKD",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","otherPIA","NPIA ",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","otherEVOtherIMRP","NEVM",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","CAMMA","CAMMABIZ",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","CAMMABIZBIZ","CAMMABIZ",Replacer.ReplaceText,{"Acronym"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","CAMOtherMBIZ","CAMMABIZ",Replacer.ReplaceText,{"Acronym"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Replaced Value7", {"Acronym"})
				in
				    #"Removed Duplicates1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

